Collections:
- Name: SimpleBaseline2D
  Paper:
    Title: Simple baselines for human pose estimation and tracking
    URL: http://openaccess.thecvf.com/content_ECCV_2018/html/Bin_Xiao_Simple_Baselines_for_ECCV_2018_paper.html
  README: https://github.com/open-mmlab/mmpose/blob/master/docs/en/papers/algorithms/simplebaseline2d.md
Models:
- Config: configs/animal/2d_kpt_sview_rgb_img/topdown_heatmap/locust/res50_locust_160x160.py
  In Collection: SimpleBaseline2D
  Metadata:
    Architecture: &id001
    - SimpleBaseline2D
    Training Data: Desert Locust
  Name: topdown_heatmap_res50_locust_160x160
  Results:
  - Dataset: Desert Locust
    Metrics:
      AUC: 0.899
      EPE: 2.27
      PCK@0.2: 0.999
    Task: Animal 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/animal/resnet/res50_locust_160x160-9efca22b_20210407.pth
- Config: configs/animal/2d_kpt_sview_rgb_img/topdown_heatmap/locust/res101_locust_160x160.py
  In Collection: SimpleBaseline2D
  Metadata:
    Architecture: *id001
    Training Data: Desert Locust
  Name: topdown_heatmap_res101_locust_160x160
  Results:
  - Dataset: Desert Locust
    Metrics:
      AUC: 0.907
      EPE: 2.03
      PCK@0.2: 0.999
    Task: Animal 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/animal/resnet/res101_locust_160x160-d77986b3_20210407.pth
- Config: configs/animal/2d_kpt_sview_rgb_img/topdown_heatmap/locust/res152_locust_160x160.py
  In Collection: SimpleBaseline2D
  Metadata:
    Architecture: *id001
    Training Data: Desert Locust
  Name: topdown_heatmap_res152_locust_160x160
  Results:
  - Dataset: Desert Locust
    Metrics:
      AUC: 0.926
      EPE: 1.48
      PCK@0.2: 1.0
    Task: Animal 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/animal/resnet/res152_locust_160x160-4ea9b372_20210407.pth
