Collections:
- Name: SimpleBaseline2D
  Paper:
    Title: Simple baselines for human pose estimation and tracking
    URL: http://openaccess.thecvf.com/content_ECCV_2018/html/Bin_Xiao_Simple_Baselines_for_ECCV_2018_paper.html
  README: https://github.com/open-mmlab/mmpose/blob/master/docs/en/papers/algorithms/simplebaseline2d.md
Models:
- Config: configs/wholebody/2d_kpt_sview_rgb_img/topdown_heatmap/coco-wholebody/res50_coco_wholebody_256x192.py
  In Collection: SimpleBaseline2D
  Metadata:
    Architecture: &id001
    - SimpleBaseline2D
    Training Data: COCO-WholeBody
  Name: topdown_heatmap_res50_coco_wholebody_256x192
  Results:
  - Dataset: COCO-WholeBody
    Metrics:
      Body AP: 0.652
      Body AR: 0.739
      Face AP: 0.608
      Face AR: 0.716
      Foot AP: 0.614
      Foot AR: 0.746
      Hand AP: 0.46
      Hand AR: 0.584
      Whole AP: 0.52
      Whole AR: 0.633
    Task: Wholebody 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/resnet/res50_coco_wholebody_256x192-9e37ed88_20201004.pth
- Config: configs/wholebody/2d_kpt_sview_rgb_img/topdown_heatmap/coco-wholebody/res50_coco_wholebody_384x288.py
  In Collection: SimpleBaseline2D
  Metadata:
    Architecture: *id001
    Training Data: COCO-WholeBody
  Name: topdown_heatmap_res50_coco_wholebody_384x288
  Results:
  - Dataset: COCO-WholeBody
    Metrics:
      Body AP: 0.666
      Body AR: 0.747
      Face AP: 0.732
      Face AR: 0.812
      Foot AP: 0.635
      Foot AR: 0.763
      Hand AP: 0.537
      Hand AR: 0.647
      Whole AP: 0.573
      Whole AR: 0.671
    Task: Wholebody 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/resnet/res50_coco_wholebody_384x288-ce11e294_20201004.pth
- Config: configs/wholebody/2d_kpt_sview_rgb_img/topdown_heatmap/coco-wholebody/res101_coco_wholebody_256x192.py
  In Collection: SimpleBaseline2D
  Metadata:
    Architecture: *id001
    Training Data: COCO-WholeBody
  Name: topdown_heatmap_res101_coco_wholebody_256x192
  Results:
  - Dataset: COCO-WholeBody
    Metrics:
      Body AP: 0.67
      Body AR: 0.754
      Face AP: 0.611
      Face AR: 0.723
      Foot AP: 0.64
      Foot AR: 0.767
      Hand AP: 0.463
      Hand AR: 0.589
      Whole AP: 0.533
      Whole AR: 0.647
    Task: Wholebody 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/resnet/res101_coco_wholebody_256x192-7325f982_20201004.pth
- Config: configs/wholebody/2d_kpt_sview_rgb_img/topdown_heatmap/coco-wholebody/res101_coco_wholebody_384x288.py
  In Collection: SimpleBaseline2D
  Metadata:
    Architecture: *id001
    Training Data: COCO-WholeBody
  Name: topdown_heatmap_res101_coco_wholebody_384x288
  Results:
  - Dataset: COCO-WholeBody
    Metrics:
      Body AP: 0.692
      Body AR: 0.77
      Face AP: 0.747
      Face AR: 0.822
      Foot AP: 0.68
      Foot AR: 0.798
      Hand AP: 0.549
      Hand AR: 0.658
      Whole AP: 0.597
      Whole AR: 0.692
    Task: Wholebody 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/resnet/res101_coco_wholebody_384x288-6c137b9a_20201004.pth
- Config: configs/wholebody/2d_kpt_sview_rgb_img/topdown_heatmap/coco-wholebody/res152_coco_wholebody_256x192.py
  In Collection: SimpleBaseline2D
  Metadata:
    Architecture: *id001
    Training Data: COCO-WholeBody
  Name: topdown_heatmap_res152_coco_wholebody_256x192
  Results:
  - Dataset: COCO-WholeBody
    Metrics:
      Body AP: 0.682
      Body AR: 0.764
      Face AP: 0.624
      Face AR: 0.728
      Foot AP: 0.662
      Foot AR: 0.788
      Hand AP: 0.482
      Hand AR: 0.606
      Whole AP: 0.548
      Whole AR: 0.661
    Task: Wholebody 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/resnet/res152_coco_wholebody_256x192-5de8ae23_20201004.pth
- Config: configs/wholebody/2d_kpt_sview_rgb_img/topdown_heatmap/coco-wholebody/res152_coco_wholebody_384x288.py
  In Collection: SimpleBaseline2D
  Metadata:
    Architecture: *id001
    Training Data: COCO-WholeBody
  Name: topdown_heatmap_res152_coco_wholebody_384x288
  Results:
  - Dataset: COCO-WholeBody
    Metrics:
      Body AP: 0.703
      Body AR: 0.78
      Face AP: 0.751
      Face AR: 0.825
      Foot AP: 0.693
      Foot AR: 0.813
      Hand AP: 0.559
      Hand AR: 0.667
      Whole AP: 0.61
      Whole AR: 0.705
    Task: Wholebody 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/resnet/res152_coco_wholebody_384x288-eab8caa8_20201004.pth
