Collections:
- Name: ViPNAS
  Paper:
    Title: 'ViPNAS: Efficient Video Pose Estimation via Neural Architecture Search'
    URL: https://arxiv.org/abs/2105.10154
  README: https://github.com/open-mmlab/mmpose/blob/master/docs/en/papers/backbones/vipnas.md
Models:
- Config: configs/wholebody/2d_kpt_sview_rgb_img/topdown_heatmap/coco-wholebody/vipnas_mbv3_coco_wholebody_256x192_dark.py
  In Collection: ViPNAS
  Metadata:
    Architecture: &id001
    - ViPNAS
    - DarkPose
    Training Data: COCO-WholeBody
  Name: topdown_heatmap_vipnas_mbv3_coco_wholebody_256x192_dark
  Results:
  - Dataset: COCO-WholeBody
    Metrics:
      Body AP: 0.632
      Body AR: 0.71
      Face AP: 0.672
      Face AR: 0.771
      Foot AP: 0.53
      Foot AR: 0.66
      Hand AP: 0.404
      Hand AR: 0.519
      Whole AP: 0.508
      Whole AR: 0.607
    Task: Wholebody 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/vipnas/vipnas_mbv3_coco_wholebody_256x192_dark-e2158108_20211205.pth
- Config: configs/wholebody/2d_kpt_sview_rgb_img/topdown_heatmap/coco-wholebody/vipnas_res50_coco_wholebody_256x192_dark.py
  In Collection: ViPNAS
  Metadata:
    Architecture: *id001
    Training Data: COCO-WholeBody
  Name: topdown_heatmap_vipnas_res50_coco_wholebody_256x192_dark
  Results:
  - Dataset: COCO-WholeBody
    Metrics:
      Body AP: 0.65
      Body AR: 0.732
      Face AP: 0.684
      Face AR: 0.784
      Foot AP: 0.55
      Foot AR: 0.686
      Hand AP: 0.437
      Hand AR: 0.554
      Whole AP: 0.528
      Whole AR: 0.632
    Task: Wholebody 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/vipnas/vipnas_res50_wholebody_256x192_dark-67c0ce35_20211112.pth
