Collections:
- Name: HRNet
  Paper:
    Title: Deep high-resolution representation learning for human pose estimation
    URL: http://openaccess.thecvf.com/content_CVPR_2019/html/Sun_Deep_High-Resolution_Representation_Learning_for_Human_Pose_Estimation_CVPR_2019_paper.html
  README: https://github.com/open-mmlab/mmpose/blob/master/docs/en/papers/backbones/hrnet.md
Models:
- Config: configs/animal/2d_kpt_sview_rgb_img/topdown_heatmap/horse10/hrnet_w32_horse10_256x256-split1.py
  In Collection: HRNet
  Metadata:
    Architecture: &id001
    - HRNet
    Training Data: Horse-10
  Name: topdown_heatmap_hrnet_w32_horse10_256x256-split1
  Results:
  - Dataset: Horse-10
    Metrics:
      NME: 0.122
      PCK@0.3: 0.951
    Task: Animal 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/animal/hrnet/hrnet_w32_horse10_256x256_split1-401d901a_20210405.pth
- Config: configs/animal/2d_kpt_sview_rgb_img/topdown_heatmap/horse10/hrnet_w32_horse10_256x256-split2.py
  In Collection: HRNet
  Metadata:
    Architecture: *id001
    Training Data: Horse-10
  Name: topdown_heatmap_hrnet_w32_horse10_256x256-split2
  Results:
  - Dataset: Horse-10
    Metrics:
      NME: 0.116
      PCK@0.3: 0.949
    Task: Animal 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/animal/hrnet/hrnet_w32_horse10_256x256_split2-04840523_20210405.pth
- Config: configs/animal/2d_kpt_sview_rgb_img/topdown_heatmap/horse10/hrnet_w32_horse10_256x256-split3.py
  In Collection: HRNet
  Metadata:
    Architecture: *id001
    Training Data: Horse-10
  Name: topdown_heatmap_hrnet_w32_horse10_256x256-split3
  Results:
  - Dataset: Horse-10
    Metrics:
      NME: 0.153
      PCK@0.3: 0.939
    Task: Animal 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/animal/hrnet/hrnet_w32_horse10_256x256_split3-4db47400_20210405.pth
- Config: configs/animal/2d_kpt_sview_rgb_img/topdown_heatmap/horse10/hrnet_w48_horse10_256x256-split1.py
  In Collection: HRNet
  Metadata:
    Architecture: *id001
    Training Data: Horse-10
  Name: topdown_heatmap_hrnet_w48_horse10_256x256-split1
  Results:
  - Dataset: Horse-10
    Metrics:
      NME: 0.095
      PCK@0.3: 0.973
    Task: Animal 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/animal/hrnet/hrnet_w48_horse10_256x256_split1-3c950d3b_20210405.pth
- Config: configs/animal/2d_kpt_sview_rgb_img/topdown_heatmap/horse10/hrnet_w48_horse10_256x256-split2.py
  In Collection: HRNet
  Metadata:
    Architecture: *id001
    Training Data: Horse-10
  Name: topdown_heatmap_hrnet_w48_horse10_256x256-split2
  Results:
  - Dataset: Horse-10
    Metrics:
      NME: 0.101
      PCK@0.3: 0.969
    Task: Animal 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/animal/hrnet/hrnet_w48_horse10_256x256_split2-8ef72b5d_20210405.pth
- Config: configs/animal/2d_kpt_sview_rgb_img/topdown_heatmap/horse10/hrnet_w48_horse10_256x256-split3.py
  In Collection: HRNet
  Metadata:
    Architecture: *id001
    Training Data: Horse-10
  Name: topdown_heatmap_hrnet_w48_horse10_256x256-split3
  Results:
  - Dataset: Horse-10
    Metrics:
      NME: 0.128
      PCK@0.3: 0.961
    Task: Animal 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/animal/hrnet/hrnet_w48_horse10_256x256_split3-0232ec47_20210405.pth
