Collections:
- Name: SimpleBaseline2D
  Paper:
    Title: Simple baselines for human pose estimation and tracking
    URL: http://openaccess.thecvf.com/content_ECCV_2018/html/Bin_Xiao_Simple_Baselines_for_ECCV_2018_paper.html
  README: https://github.com/open-mmlab/mmpose/blob/master/docs/en/papers/algorithms/simplebaseline2d.md
Models:
- Config: configs/animal/2d_kpt_sview_rgb_img/topdown_heatmap/horse10/res50_horse10_256x256-split1.py
  In Collection: SimpleBaseline2D
  Metadata:
    Architecture: &id001
    - SimpleBaseline2D
    Training Data: Horse-10
  Name: topdown_heatmap_res50_horse10_256x256-split1
  Results:
  - Dataset: Horse-10
    Metrics:
      NME: 0.113
      PCK@0.3: 0.956
    Task: Animal 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/animal/resnet/res50_horse10_256x256_split1-3a3dc37e_20210405.pth
- Config: configs/animal/2d_kpt_sview_rgb_img/topdown_heatmap/horse10/res50_horse10_256x256-split2.py
  In Collection: SimpleBaseline2D
  Metadata:
    Architecture: *id001
    Training Data: Horse-10
  Name: topdown_heatmap_res50_horse10_256x256-split2
  Results:
  - Dataset: Horse-10
    Metrics:
      NME: 0.111
      PCK@0.3: 0.954
    Task: Animal 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/animal/resnet/res50_horse10_256x256_split2-65e2a508_20210405.pth
- Config: configs/animal/2d_kpt_sview_rgb_img/topdown_heatmap/horse10/res50_horse10_256x256-split3.py
  In Collection: SimpleBaseline2D
  Metadata:
    Architecture: *id001
    Training Data: Horse-10
  Name: topdown_heatmap_res50_horse10_256x256-split3
  Results:
  - Dataset: Horse-10
    Metrics:
      NME: 0.129
      PCK@0.3: 0.946
    Task: Animal 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/animal/resnet/res50_horse10_256x256_split3-9637d4eb_20210405.pth
- Config: configs/animal/2d_kpt_sview_rgb_img/topdown_heatmap/horse10/res101_horse10_256x256-split1.py
  In Collection: SimpleBaseline2D
  Metadata:
    Architecture: *id001
    Training Data: Horse-10
  Name: topdown_heatmap_res101_horse10_256x256-split1
  Results:
  - Dataset: Horse-10
    Metrics:
      NME: 0.115
      PCK@0.3: 0.958
    Task: Animal 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/animal/resnet/res101_horse10_256x256_split1-1b7c259c_20210405.pth
- Config: configs/animal/2d_kpt_sview_rgb_img/topdown_heatmap/horse10/res101_horse10_256x256-split2.py
  In Collection: SimpleBaseline2D
  Metadata:
    Architecture: *id001
    Training Data: Horse-10
  Name: topdown_heatmap_res101_horse10_256x256-split2
  Results:
  - Dataset: Horse-10
    Metrics:
      NME: 0.115
      PCK@0.3: 0.955
    Task: Animal 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/animal/resnet/res101_horse10_256x256_split2-30e2fa87_20210405.pth
- Config: configs/animal/2d_kpt_sview_rgb_img/topdown_heatmap/horse10/res101_horse10_256x256-split3.py
  In Collection: SimpleBaseline2D
  Metadata:
    Architecture: *id001
    Training Data: Horse-10
  Name: topdown_heatmap_res101_horse10_256x256-split3
  Results:
  - Dataset: Horse-10
    Metrics:
      NME: 0.126
      PCK@0.3: 0.946
    Task: Animal 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/animal/resnet/res101_horse10_256x256_split3-2eea5bb1_20210405.pth
- Config: configs/animal/2d_kpt_sview_rgb_img/topdown_heatmap/horse10/res152_horse10_256x256-split1.py
  In Collection: SimpleBaseline2D
  Metadata:
    Architecture: *id001
    Training Data: Horse-10
  Name: topdown_heatmap_res152_horse10_256x256-split1
  Results:
  - Dataset: Horse-10
    Metrics:
      NME: 0.105
      PCK@0.3: 0.969
    Task: Animal 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/animal/resnet/res152_horse10_256x256_split1-7e81fe2d_20210405.pth
- Config: configs/animal/2d_kpt_sview_rgb_img/topdown_heatmap/horse10/res152_horse10_256x256-split2.py
  In Collection: SimpleBaseline2D
  Metadata:
    Architecture: *id001
    Training Data: Horse-10
  Name: topdown_heatmap_res152_horse10_256x256-split2
  Results:
  - Dataset: Horse-10
    Metrics:
      NME: 0.103
      PCK@0.3: 0.97
    Task: Animal 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/animal/resnet/res152_horse10_256x256_split2-3b3404a3_20210405.pth
- Config: configs/animal/2d_kpt_sview_rgb_img/topdown_heatmap/horse10/res152_horse10_256x256-split3.py
  In Collection: SimpleBaseline2D
  Metadata:
    Architecture: *id001
    Training Data: Horse-10
  Name: topdown_heatmap_res152_horse10_256x256-split3
  Results:
  - Dataset: Horse-10
    Metrics:
      NME: 0.131
      PCK@0.3: 0.957
    Task: Animal 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/animal/resnet/res152_horse10_256x256_split3-c957dac5_20210405.pth
