Collections:
- Name: PoseWarper
  Paper:
    Title: Learning Temporal Pose Estimation from Sparsely Labeled Videos
    URL: https://arxiv.org/abs/1906.04016
  README: https://github.com/open-mmlab/mmpose/blob/master/docs/en/papers/algorithms/posewarper.md
Models:
- Config: configs/body/2d_kpt_sview_rgb_vid/posewarper/posetrack18/hrnet_w48_posetrack18_384x288_posewarper_stage2.py
  In Collection: PoseWarper
  Metadata:
    Architecture: &id001
    - PoseWarper
    - HRNet
    Training Data: COCO
  Name: posewarper_hrnet_w48_posetrack18_384x288_posewarper_stage2
  Results:
  - Dataset: COCO
    Metrics:
      Ankl: 81.5
      Elb: 86.1
      Head: 88.2
      Hip: 81.8
      Knee: 83.8
      Shou: 90.3
      Total: 85.0
      Wri: 81.6
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/posewarper/hrnet_w48_posetrack18_384x288_posewarper_stage2-4abf88db_20211130.pth
- Config: configs/body/2d_kpt_sview_rgb_vid/posewarper/posetrack18/hrnet_w48_posetrack18_384x288_posewarper_stage2.py
  In Collection: PoseWarper
  Metadata:
    Architecture: *id001
    Training Data: COCO
  Name: posewarper_hrnet_w48_posetrack18_384x288_posewarper_stage2
  Results:
  - Dataset: COCO
    Metrics:
      Ankl: 74.4
      Elb: 82.7
      Head: 81.8
      Hip: 76.8
      Knee: 79.0
      Shou: 85.6
      Total: 79.8
      Wri: 77.2
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/posewarper/hrnet_w48_posetrack18_384x288_posewarper_stage2-4abf88db_20211130.pth
