Collections:
- Name: Hourglass
  Paper:
    Title: Stacked hourglass networks for human pose estimation
    URL: https://link.springer.com/chapter/10.1007/978-3-319-46484-8_29
  README: https://github.com/open-mmlab/mmpose/blob/master/docs/en/papers/backbones/hourglass.md
Models:
- Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/mpii/hourglass52_mpii_256x256.py
  In Collection: Hourglass
  Metadata:
    Architecture: &id001
    - Hourglass
    Training Data: MPII
  Name: topdown_heatmap_hourglass52_mpii_256x256
  Results:
  - Dataset: MPII
    Metrics:
      Mean: 0.889
      Mean@0.1: 0.317
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/hourglass/hourglass52_mpii_256x256-ae358435_20200812.pth
- Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/mpii/hourglass52_mpii_384x384.py
  In Collection: Hourglass
  Metadata:
    Architecture: *id001
    Training Data: MPII
  Name: topdown_heatmap_hourglass52_mpii_384x384
  Results:
  - Dataset: MPII
    Metrics:
      Mean: 0.894
      Mean@0.1: 0.366
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/hourglass/hourglass52_mpii_384x384-04090bc3_20200812.pth
