Collections:
- Name: DarkPose
  Paper:
    Title: Distribution-aware coordinate representation for human pose estimation
    URL: http://openaccess.thecvf.com/content_CVPR_2020/html/Zhang_Distribution-Aware_Coordinate_Representation_for_Human_Pose_Estimation_CVPR_2020_paper.html
  README: https://github.com/open-mmlab/mmpose/blob/master/docs/en/papers/techniques/dark.md
Models:
- Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/mpii/hrnet_w32_mpii_256x256_dark.py
  In Collection: DarkPose
  Metadata:
    Architecture: &id001
    - HRNet
    - DarkPose
    Training Data: MPII
  Name: topdown_heatmap_hrnet_w32_mpii_256x256_dark
  Results:
  - Dataset: MPII
    Metrics:
      Mean: 0.904
      Mean@0.1: 0.354
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/hrnet/hrnet_w32_mpii_256x256_dark-f1601c5b_20200927.pth
- Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/mpii/hrnet_w48_mpii_256x256_dark.py
  In Collection: DarkPose
  Metadata:
    Architecture: *id001
    Training Data: MPII
  Name: topdown_heatmap_hrnet_w48_mpii_256x256_dark
  Results:
  - Dataset: MPII
    Metrics:
      Mean: 0.905
      Mean@0.1: 0.36
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/hrnet/hrnet_w48_mpii_256x256_dark-0decd39f_20200927.pth
