Collections:
- Name: LiteHRNet
  Paper:
    Title: 'Lite-HRNet: A Lightweight High-Resolution Network'
    URL: https://arxiv.org/abs/2104.06403
  README: https://github.com/open-mmlab/mmpose/blob/master/docs/en/papers/backbones/litehrnet.md
Models:
- Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/mpii/litehrnet_18_mpii_256x256.py
  In Collection: LiteHRNet
  Metadata:
    Architecture: &id001
    - LiteHRNet
    Training Data: MPII
  Name: topdown_heatmap_litehrnet_18_mpii_256x256
  Results:
  - Dataset: MPII
    Metrics:
      Mean: 0.859
      Mean@0.1: 0.26
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/litehrnet/litehrnet18_mpii_256x256-cabd7984_20210623.pth
- Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/mpii/litehrnet_30_mpii_256x256.py
  In Collection: LiteHRNet
  Metadata:
    Architecture: *id001
    Training Data: MPII
  Name: topdown_heatmap_litehrnet_30_mpii_256x256
  Results:
  - Dataset: MPII
    Metrics:
      Mean: 0.869
      Mean@0.1: 0.271
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/litehrnet/litehrnet30_mpii_256x256-faae8bd8_20210622.pth
