Collections:
- Name: ResNetV1D
  Paper:
    Title: Bag of tricks for image classification with convolutional neural networks
    URL: http://openaccess.thecvf.com/content_CVPR_2019/html/He_Bag_of_Tricks_for_Image_Classification_with_Convolutional_Neural_Networks_CVPR_2019_paper.html
  README: https://github.com/open-mmlab/mmpose/blob/master/docs/en/papers/backbones/resnetv1d.md
Models:
- Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/mpii/resnetv1d50_mpii_256x256.py
  In Collection: ResNetV1D
  Metadata:
    Architecture: &id001
    - ResNetV1D
    Training Data: MPII
  Name: topdown_heatmap_resnetv1d50_mpii_256x256
  Results:
  - Dataset: MPII
    Metrics:
      Mean: 0.881
      Mean@0.1: 0.29
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/resnetv1d/resnetv1d50_mpii_256x256-2337a92e_20200812.pth
- Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/mpii/resnetv1d101_mpii_256x256.py
  In Collection: ResNetV1D
  Metadata:
    Architecture: *id001
    Training Data: MPII
  Name: topdown_heatmap_resnetv1d101_mpii_256x256
  Results:
  - Dataset: MPII
    Metrics:
      Mean: 0.883
      Mean@0.1: 0.295
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/resnetv1d/resnetv1d101_mpii_256x256-2851d710_20200812.pth
- Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/mpii/resnetv1d152_mpii_256x256.py
  In Collection: ResNetV1D
  Metadata:
    Architecture: *id001
    Training Data: MPII
  Name: topdown_heatmap_resnetv1d152_mpii_256x256
  Results:
  - Dataset: MPII
    Metrics:
      Mean: 0.888
      Mean@0.1: 0.3
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/resnetv1d/resnetv1d152_mpii_256x256-8b10a87c_20200812.pth
