Collections:
- Name: SimpleBaseline2D
  Paper:
    Title: Simple baselines for human pose estimation and tracking
    URL: http://openaccess.thecvf.com/content_ECCV_2018/html/Bin_Xiao_Simple_Baselines_for_ECCV_2018_paper.html
  README: https://github.com/open-mmlab/mmpose/blob/master/docs/en/papers/algorithms/simplebaseline2d.md
Models:
- Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/mpii/res50_mpii_256x256.py
  In Collection: SimpleBaseline2D
  Metadata:
    Architecture: &id001
    - SimpleBaseline2D
    - ResNet
    Training Data: MPII
  Name: topdown_heatmap_res50_mpii_256x256
  Results:
  - Dataset: MPII
    Metrics:
      Mean: 0.882
      Mean@0.1: 0.286
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/resnet/res50_mpii_256x256-418ffc88_20200812.pth
- Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/mpii/res101_mpii_256x256.py
  In Collection: SimpleBaseline2D
  Metadata:
    Architecture: *id001
    Training Data: MPII
  Name: topdown_heatmap_res101_mpii_256x256
  Results:
  - Dataset: MPII
    Metrics:
      Mean: 0.888
      Mean@0.1: 0.29
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/resnet/res101_mpii_256x256-416f5d71_20200812.pth
- Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/mpii/res152_mpii_256x256.py
  In Collection: SimpleBaseline2D
  Metadata:
    Architecture: *id001
    Training Data: MPII
  Name: topdown_heatmap_res152_mpii_256x256
  Results:
  - Dataset: MPII
    Metrics:
      Mean: 0.889
      Mean@0.1: 0.303
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/resnet/res152_mpii_256x256-3ecba29d_20200812.pth
