Collections:
- Name: SCNet
  Paper:
    Title: Improving Convolutional Networks with Self-Calibrated Convolutions
    URL: http://openaccess.thecvf.com/content_CVPR_2020/html/Liu_Improving_Convolutional_Networks_With_Self-Calibrated_Convolutions_CVPR_2020_paper.html
  README: https://github.com/open-mmlab/mmpose/blob/master/docs/en/papers/backbones/scnet.md
Models:
- Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/mpii/scnet50_mpii_256x256.py
  In Collection: SCNet
  Metadata:
    Architecture: &id001
    - SCNet
    Training Data: MPII
  Name: topdown_heatmap_scnet50_mpii_256x256
  Results:
  - Dataset: MPII
    Metrics:
      Mean: 0.888
      Mean@0.1: 0.29
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/scnet/scnet50_mpii_256x256-a54b6af5_20200812.pth
- Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/mpii/scnet101_mpii_256x256.py
  In Collection: SCNet
  Metadata:
    Architecture: *id001
    Training Data: MPII
  Name: topdown_heatmap_scnet101_mpii_256x256
  Results:
  - Dataset: MPII
    Metrics:
      Mean: 0.886
      Mean@0.1: 0.293
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/scnet/scnet101_mpii_256x256-b4c2d184_20200812.pth
