Collections:
- Name: SEResNet
  Paper:
    Title: Squeeze-and-excitation networks
    URL: http://openaccess.thecvf.com/content_cvpr_2018/html/Hu_Squeeze-and-Excitation_Networks_CVPR_2018_paper
  README: https://github.com/open-mmlab/mmpose/blob/master/docs/en/papers/backbones/seresnet.md
Models:
- Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/mpii/seresnet50_mpii_256x256.py
  In Collection: SEResNet
  Metadata:
    Architecture: &id001
    - SEResNet
    Training Data: MPII
  Name: topdown_heatmap_seresnet50_mpii_256x256
  Results:
  - Dataset: MPII
    Metrics:
      Mean: 0.884
      Mean@0.1: 0.292
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/seresnet/seresnet50_mpii_256x256-1bb21f79_20200927.pth
- Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/mpii/seresnet101_mpii_256x256.py
  In Collection: SEResNet
  Metadata:
    Architecture: *id001
    Training Data: MPII
  Name: topdown_heatmap_seresnet101_mpii_256x256
  Results:
  - Dataset: MPII
    Metrics:
      Mean: 0.884
      Mean@0.1: 0.295
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/seresnet/seresnet101_mpii_256x256-0ba14ff5_20200927.pth
- Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/mpii/seresnet152_mpii_256x256.py
  In Collection: SEResNet
  Metadata:
    Architecture: *id001
    Training Data: MPII
  Name: topdown_heatmap_seresnet152_mpii_256x256
  Results:
  - Dataset: MPII
    Metrics:
      Mean: 0.884
      Mean@0.1: 0.287
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/seresnet/seresnet152_mpii_256x256-6ea1e774_20200927.pth
