Collections:
- Name: HigherHRNet
  Paper:
    Title: 'HigherHRNet: Scale-Aware Representation Learning for Bottom-Up Human Pose
      Estimation'
    URL: http://openaccess.thecvf.com/content_CVPR_2020/html/Cheng_HigherHRNet_Scale-Aware_Representation_Learning_for_Bottom-Up_Human_Pose_Estimation_CVPR_2020_paper.html
  README: https://github.com/open-mmlab/mmpose/blob/master/docs/en/papers/backbones/higherhrnet.md
Models:
- Config: configs/body/2d_kpt_sview_rgb_img/associative_embedding/crowdpose/higherhrnet_w32_crowdpose_512x512.py
  In Collection: HigherHRNet
  Metadata:
    Architecture: &id001
    - Associative Embedding
    - HigherHRNet
    Training Data: CrowdPose
  Name: associative_embedding_higherhrnet_w32_crowdpose_512x512
  Results:
  - Dataset: CrowdPose
    Metrics:
      AP: 0.655
      AP (E): 0.728
      AP (H): 0.577
      AP (M): 0.66
      AP@0.5: 0.859
      AP@0.75: 0.705
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/bottom_up/higher_hrnet32_crowdpose_512x512-1aa4a132_20201017.pth
- Config: configs/body/2d_kpt_sview_rgb_img/associative_embedding/crowdpose/higherhrnet_w32_crowdpose_512x512.py
  In Collection: HigherHRNet
  Metadata:
    Architecture: *id001
    Training Data: CrowdPose
  Name: associative_embedding_higherhrnet_w32_crowdpose_512x512
  Results:
  - Dataset: CrowdPose
    Metrics:
      AP: 0.661
      AP (E): 0.742
      AP (H): 0.566
      AP (M): 0.67
      AP@0.5: 0.864
      AP@0.75: 0.71
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/bottom_up/higher_hrnet32_crowdpose_512x512-1aa4a132_20201017.pth
