Collections:
- Name: DarkPose
  Paper:
    Title: Distribution-aware coordinate representation for human pose estimation
    URL: http://openaccess.thecvf.com/content_CVPR_2020/html/Zhang_Distribution-Aware_Coordinate_Representation_for_Human_Pose_Estimation_CVPR_2020_paper.html
  README: https://github.com/open-mmlab/mmpose/blob/master/docs/en/papers/techniques/dark.md
Models:
- Config: configs/hand/2d_kpt_sview_rgb_img/topdown_heatmap/coco_wholebody_hand/hrnetv2_w18_coco_wholebody_hand_256x256_dark.py
  In Collection: DarkPose
  Metadata:
    Architecture:
    - HRNetv2
    - DarkPose
    Training Data: COCO-WholeBody-Hand
  Name: topdown_heatmap_hrnetv2_w18_coco_wholebody_hand_256x256_dark
  Results:
  - Dataset: COCO-WholeBody-Hand
    Metrics:
      AUC: 0.84
      EPE: 4.37
      PCK@0.2: 0.814
    Task: Hand 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/hand/dark/hrnetv2_w18_coco_wholebody_hand_256x256_dark-a9228c9c_20210908.pth
