Collections:
- Name: MobilenetV2
  Paper:
    Title: 'Mobilenetv2: Inverted residuals and linear bottlenecks'
    URL: http://openaccess.thecvf.com/content_cvpr_2018/html/Sandler_MobileNetV2_Inverted_Residuals_CVPR_2018_paper.html
  README: https://github.com/open-mmlab/mmpose/blob/master/docs/en/papers/backbones/mobilenetv2.md
Models:
- Config: configs/hand/2d_kpt_sview_rgb_img/topdown_heatmap/coco_wholebody_hand/mobilenetv2_coco_wholebody_hand_256x256.py
  In Collection: MobilenetV2
  Metadata:
    Architecture:
    - MobilenetV2
    Training Data: COCO-WholeBody-Hand
  Name: topdown_heatmap_mobilenetv2_coco_wholebody_hand_256x256
  Results:
  - Dataset: COCO-WholeBody-Hand
    Metrics:
      AUC: 0.829
      EPE: 4.77
      PCK@0.2: 0.795
    Task: Hand 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/hand/mobilenetv2/mobilenetv2_coco_wholebody_hand_256x256-06b8c877_20210909.pth
