fps: 30
force_yes: false
io:
  filter_completed: true
  video_dir_path: /datasets01/ego4d_track2/v1/full_scale/
  ego4d_download_dir: /checkpoint/miguelmartin/ego4d/
  uid_list: null
  video_limit: -1
  out_path: /checkpoint/miguelmartin/ego4d_track2_features/full_scale/audio_mel_spectrogram
  debug_path: /checkpoint/miguelmartin/ego4d_track2_features/full_scale/audio_mel_spectrogram_debug
  debug_mode: false
  exclude_no_audio: true
  dataset_version: ego4d
inference_config:
  device: cpu
  batch_size: 1
  num_workers: 0
  prefetch_factor: 2
  fps: 30
  frame_window: 100000000
  stride: 100000000
  include_audio: true
  include_video: false
  norm_config:
    normalize_audio: true
    resample_audio_rate: 16000
    resampling_method: "sinc_interpolation"
schedule_config:
  run_locally: false
  log_folder: slurm_log/%j
  timeout_min: 720
  constraint: volta
  slurm_partition: pixar
  slurm_array_parallelism: 10
  gpus_per_node: 1
  cpus_per_task: 10
  overhead: 1.0
  time_per_forward_pass: 100
  schedule_time_per_node: 10.0
model_config:
  n_fft: 1024
  win_length: null
  hop_length: 160
  n_mels: 128
model_module_str: ego4d.features.models.mel_spectrogram
