Collections:
- Name: HigherHRNet
  Paper:
    Title: 'HigherHRNet: Scale-Aware Representation Learning for Bottom-Up Human Pose
      Estimation'
    URL: http://openaccess.thecvf.com/content_CVPR_2020/html/Cheng_HigherHRNet_Scale-Aware_Representation_Learning_for_Bottom-Up_Human_Pose_Estimation_CVPR_2020_paper.html
  README: https://github.com/open-mmlab/mmpose/blob/master/docs/en/papers/backbones/higherhrnet.md
Models:
- Config: configs/body/2d_kpt_sview_rgb_img/associative_embedding/aic/higherhrnet_w32_aic_512x512.py
  In Collection: HigherHRNet
  Metadata:
    Architecture: &id001
    - Associative Embedding
    - HigherHRNet
    Training Data: AI Challenger
  Name: associative_embedding_higherhrnet_w32_aic_512x512
  Results:
  - Dataset: AI Challenger
    Metrics:
      AP: 0.315
      AP@0.5: 0.71
      AP@0.75: 0.243
      AR: 0.379
      AR@0.5: 0.757
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/bottom_up/higher_hrnet32_aic_512x512-9a674c33_20210130.pth
- Config: configs/body/2d_kpt_sview_rgb_img/associative_embedding/aic/higherhrnet_w32_aic_512x512.py
  In Collection: HigherHRNet
  Metadata:
    Architecture: *id001
    Training Data: AI Challenger
  Name: associative_embedding_higherhrnet_w32_aic_512x512
  Results:
  - Dataset: AI Challenger
    Metrics:
      AP: 0.323
      AP@0.5: 0.718
      AP@0.75: 0.254
      AR: 0.379
      AR@0.5: 0.758
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/bottom_up/higher_hrnet32_aic_512x512-9a674c33_20210130.pth
