Collections:
- Name: HRNet
  Paper:
    Title: Deep high-resolution representation learning for human pose estimation
    URL: http://openaccess.thecvf.com/content_CVPR_2019/html/Sun_Deep_High-Resolution_Representation_Learning_for_Human_Pose_Estimation_CVPR_2019_paper.html
  README: https://github.com/open-mmlab/mmpose/blob/master/docs/en/papers/backbones/hrnet.md
Models:
- Config: configs/body/2d_kpt_sview_rgb_img/associative_embedding/aic/hrnet_w32_aic_512x512.py
  In Collection: HRNet
  Metadata:
    Architecture: &id001
    - Associative Embedding
    - HRNet
    Training Data: AI Challenger
  Name: associative_embedding_hrnet_w32_aic_512x512
  Results:
  - Dataset: AI Challenger
    Metrics:
      AP: 0.303
      AP@0.5: 0.697
      AP@0.75: 0.225
      AR: 0.373
      AR@0.5: 0.755
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/bottom_up/hrnet_w32_aic_512x512-77e2a98a_20210131.pth
- Config: configs/body/2d_kpt_sview_rgb_img/associative_embedding/aic/hrnet_w32_aic_512x512.py
  In Collection: HRNet
  Metadata:
    Architecture: *id001
    Training Data: AI Challenger
  Name: associative_embedding_hrnet_w32_aic_512x512
  Results:
  - Dataset: AI Challenger
    Metrics:
      AP: 0.318
      AP@0.5: 0.717
      AP@0.75: 0.246
      AR: 0.379
      AR@0.5: 0.764
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/bottom_up/hrnet_w32_aic_512x512-77e2a98a_20210131.pth
