Collections:
- Name: HRNet
  Paper:
    Title: Deep high-resolution representation learning for human pose estimation
    URL: http://openaccess.thecvf.com/content_CVPR_2019/html/Sun_Deep_High-Resolution_Representation_Learning_for_Human_Pose_Estimation_CVPR_2019_paper.html
  README: https://github.com/open-mmlab/mmpose/blob/master/docs/en/papers/backbones/hrnet.md
Models:
- Config: configs/animal/2d_kpt_sview_rgb_img/topdown_heatmap/animalpose/hrnet_w32_animalpose_256x256.py
  In Collection: HRNet
  Metadata:
    Architecture: &id001
    - HRNet
    Training Data: Animal-Pose
  Name: topdown_heatmap_hrnet_w32_animalpose_256x256
  Results:
  - Dataset: Animal-Pose
    Metrics:
      AP: 0.736
      AP@0.5: 0.959
      AP@0.75: 0.832
      AR: 0.775
      AR@0.5: 0.966
    Task: Animal 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/animal/hrnet/hrnet_w32_animalpose_256x256-1aa7f075_20210426.pth
- Config: configs/animal/2d_kpt_sview_rgb_img/topdown_heatmap/animalpose/hrnet_w48_animalpose_256x256.py
  In Collection: HRNet
  Metadata:
    Architecture: *id001
    Training Data: Animal-Pose
  Name: topdown_heatmap_hrnet_w48_animalpose_256x256
  Results:
  - Dataset: Animal-Pose
    Metrics:
      AP: 0.737
      AP@0.5: 0.959
      AP@0.75: 0.823
      AR: 0.778
      AR@0.5: 0.962
    Task: Animal 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/animal/hrnet/hrnet_w48_animalpose_256x256-34644726_20210426.pth
