Collections:
- Name: HRNet
  Paper:
    Title: Deep high-resolution representation learning for human pose estimation
    URL: http://openaccess.thecvf.com/content_CVPR_2019/html/Sun_Deep_High-Resolution_Representation_Learning_for_Human_Pose_Estimation_CVPR_2019_paper.html
  README: https://github.com/open-mmlab/mmpose/blob/master/docs/en/papers/backbones/hrnet.md
Models:
- Config: configs/animal/2d_kpt_sview_rgb_img/topdown_heatmap/atrw/hrnet_w32_atrw_256x256.py
  In Collection: HRNet
  Metadata:
    Architecture: &id001
    - HRNet
    Training Data: ATRW
  Name: topdown_heatmap_hrnet_w32_atrw_256x256
  Results:
  - Dataset: ATRW
    Metrics:
      AP: 0.912
      AP@0.5: 0.973
      AP@0.75: 0.959
      AR: 0.938
      AR@0.5: 0.985
    Task: Animal 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/animal/hrnet/hrnet_w32_atrw_256x256-f027f09a_20210414.pth
- Config: configs/animal/2d_kpt_sview_rgb_img/topdown_heatmap/atrw/hrnet_w48_atrw_256x256.py
  In Collection: HRNet
  Metadata:
    Architecture: *id001
    Training Data: ATRW
  Name: topdown_heatmap_hrnet_w48_atrw_256x256
  Results:
  - Dataset: ATRW
    Metrics:
      AP: 0.911
      AP@0.5: 0.972
      AP@0.75: 0.946
      AR: 0.937
      AR@0.5: 0.985
    Task: Animal 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/animal/hrnet/hrnet_w48_atrw_256x256-ac088892_20210414.pth
