Collections:
- Name: SimpleBaseline2D
  Paper:
    Title: Simple baselines for human pose estimation and tracking
    URL: http://openaccess.thecvf.com/content_ECCV_2018/html/Bin_Xiao_Simple_Baselines_for_ECCV_2018_paper.html
  README: https://github.com/open-mmlab/mmpose/blob/master/docs/en/papers/algorithms/simplebaseline2d.md
Models:
- Config: configs/animal/2d_kpt_sview_rgb_img/topdown_heatmap/atrw/res50_atrw_256x256.py
  In Collection: SimpleBaseline2D
  Metadata:
    Architecture: &id001
    - SimpleBaseline2D
    Training Data: ATRW
  Name: topdown_heatmap_res50_atrw_256x256
  Results:
  - Dataset: ATRW
    Metrics:
      AP: 0.9
      AP@0.5: 0.973
      AP@0.75: 0.932
      AR: 0.929
      AR@0.5: 0.985
    Task: Animal 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/animal/resnet/res50_atrw_256x256-546c4594_20210414.pth
- Config: configs/animal/2d_kpt_sview_rgb_img/topdown_heatmap/atrw/res101_atrw_256x256.py
  In Collection: SimpleBaseline2D
  Metadata:
    Architecture: *id001
    Training Data: ATRW
  Name: topdown_heatmap_res101_atrw_256x256
  Results:
  - Dataset: ATRW
    Metrics:
      AP: 0.898
      AP@0.5: 0.973
      AP@0.75: 0.936
      AR: 0.927
      AR@0.5: 0.985
    Task: Animal 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/animal/resnet/res101_atrw_256x256-da93f371_20210414.pth
- Config: configs/animal/2d_kpt_sview_rgb_img/topdown_heatmap/atrw/res152_atrw_256x256.py
  In Collection: SimpleBaseline2D
  Metadata:
    Architecture: *id001
    Training Data: ATRW
  Name: topdown_heatmap_res152_atrw_256x256
  Results:
  - Dataset: ATRW
    Metrics:
      AP: 0.896
      AP@0.5: 0.973
      AP@0.75: 0.931
      AR: 0.927
      AR@0.5: 0.985
    Task: Animal 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/animal/resnet/res152_atrw_256x256-2bb8e162_20210414.pth
