Collections:
- Name: ResNet
  Paper:
    Title: Deep residual learning for image recognition
    URL: http://openaccess.thecvf.com/content_cvpr_2016/html/He_Deep_Residual_Learning_CVPR_2016_paper.html
  README: https://github.com/open-mmlab/mmpose/blob/master/docs/en/papers/backbones/resnet.md
Models:
- Config: configs/fashion/2d_kpt_sview_rgb_img/deeppose/deepfashion/res50_deepfashion_upper_256x192.py
  In Collection: ResNet
  Metadata:
    Architecture: &id001
    - DeepPose
    - ResNet
    Training Data: DeepFashion
  Name: deeppose_res50_deepfashion_upper_256x192
  Results:
  - Dataset: DeepFashion
    Metrics:
      AUC: 0.535
      EPE: 17.2
      PCK@0.2: 0.965
    Task: Fashion 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/fashion/deeppose/deeppose_res50_deepfashion_upper_256x192-497799fb_20210309.pth
- Config: configs/fashion/2d_kpt_sview_rgb_img/deeppose/deepfashion/res50_deepfashion_lower_256x192.py
  In Collection: ResNet
  Metadata:
    Architecture: *id001
    Training Data: DeepFashion
  Name: deeppose_res50_deepfashion_lower_256x192
  Results:
  - Dataset: DeepFashion
    Metrics:
      AUC: 0.678
      EPE: 11.8
      PCK@0.2: 0.971
    Task: Fashion 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/fashion/deeppose/deeppose_res50_deepfashion_lower_256x192-94e0e653_20210309.pth
- Config: configs/fashion/2d_kpt_sview_rgb_img/deeppose/deepfashion/res50_deepfashion_full_256x192.py
  In Collection: ResNet
  Metadata:
    Architecture: *id001
    Training Data: DeepFashion
  Name: deeppose_res50_deepfashion_full_256x192
  Results:
  - Dataset: DeepFashion
    Metrics:
      AUC: 0.602
      EPE: 14.0
      PCK@0.2: 0.983
    Task: Fashion 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/fashion/deeppose/deeppose_res50_deepfashion_full_256x192-4e0273e2_20210309.pth
