Collections:
- Name: UDP
  Paper:
    Title: 'The Devil Is in the Details: Delving Into Unbiased Data Processing for
      Human Pose Estimation'
    URL: http://openaccess.thecvf.com/content_CVPR_2020/html/Huang_The_Devil_Is_in_the_Details_Delving_Into_Unbiased_Data_CVPR_2020_paper.html
  README: https://github.com/open-mmlab/mmpose/blob/master/docs/en/papers/techniques/udp.md
Models:
- Config: configs/hand/2d_kpt_sview_rgb_img/topdown_heatmap/onehand10k/hrnetv2_w18_onehand10k_256x256_udp.py
  In Collection: UDP
  Metadata:
    Architecture:
    - HRNetv2
    - UDP
    Training Data: OneHand10K
  Name: topdown_heatmap_hrnetv2_w18_onehand10k_256x256_udp
  Results:
  - Dataset: OneHand10K
    Metrics:
      AUC: 0.572
      EPE: 23.87
      PCK@0.2: 0.99
    Task: Hand 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/hand/udp/hrnetv2_w18_onehand10k_256x256_udp-0d1b515d_20210330.pth
