Collections:
- Name: MobilenetV2
  Paper:
    Title: 'Mobilenetv2: Inverted residuals and linear bottlenecks'
    URL: http://openaccess.thecvf.com/content_cvpr_2018/html/Sandler_MobileNetV2_Inverted_Residuals_CVPR_2018_paper.html
  README: https://github.com/open-mmlab/mmpose/blob/master/docs/en/papers/backbones/mobilenetv2.md
Models:
- Config: configs/hand/2d_kpt_sview_rgb_img/topdown_heatmap/onehand10k/mobilenetv2_onehand10k_256x256.py
  In Collection: MobilenetV2
  Metadata:
    Architecture:
    - MobilenetV2
    Training Data: OneHand10K
  Name: topdown_heatmap_mobilenetv2_onehand10k_256x256
  Results:
  - Dataset: OneHand10K
    Metrics:
      AUC: 0.537
      EPE: 28.6
      PCK@0.2: 0.986
    Task: Hand 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/hand/mobilenetv2/mobilenetv2_onehand10k_256x256-f3a3d90e_20210330.pth
