Collections:
- Name: HigherHRNet
  Paper:
    Title: 'HigherHRNet: Scale-Aware Representation Learning for Bottom-Up Human Pose
      Estimation'
    URL: http://openaccess.thecvf.com/content_CVPR_2020/html/Cheng_HigherHRNet_Scale-Aware_Representation_Learning_for_Bottom-Up_Human_Pose_Estimation_CVPR_2020_paper.html
  README: https://github.com/open-mmlab/mmpose/blob/master/docs/en/papers/backbones/higherhrnet.md
Models:
- Config: configs/body/2d_kpt_sview_rgb_img/associative_embedding/coco/higherhrnet_w32_coco_512x512_udp.py
  In Collection: HigherHRNet
  Metadata:
    Architecture: &id001
    - Associative Embedding
    - HigherHRNet
    - UDP
    Training Data: COCO
  Name: associative_embedding_higherhrnet_w32_coco_512x512_udp
  Results:
  - Dataset: COCO
    Metrics:
      AP: 0.678
      AP@0.5: 0.862
      AP@0.75: 0.736
      AR: 0.724
      AR@0.5: 0.89
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/bottom_up/higher_hrnet32_coco_512x512_udp-8cc64794_20210222.pth
- Config: configs/body/2d_kpt_sview_rgb_img/associative_embedding/coco/higherhrnet_w48_coco_512x512_udp.py
  In Collection: HigherHRNet
  Metadata:
    Architecture: *id001
    Training Data: COCO
  Name: associative_embedding_higherhrnet_w48_coco_512x512_udp
  Results:
  - Dataset: COCO
    Metrics:
      AP: 0.69
      AP@0.5: 0.872
      AP@0.75: 0.75
      AR: 0.734
      AR@0.5: 0.891
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/bottom_up/higher_hrnet48_coco_512x512_udp-7cad61ef_20210222.pth
