Collections:
- Name: Associative Embedding
  Paper:
    Title: 'Associative embedding: End-to-end learning for joint detection and grouping'
    URL: https://arxiv.org/abs/1611.05424
  README: https://github.com/open-mmlab/mmpose/blob/master/docs/en/papers/algorithms/associative_embedding.md
Models:
- Config: configs/body/2d_kpt_sview_rgb_img/associative_embedding/coco/hourglass_ae_coco_512x512.py
  In Collection: Associative Embedding
  Metadata:
    Architecture: &id001
    - Associative Embedding
    - HourglassAENet
    Training Data: COCO
  Name: associative_embedding_hourglass_ae_coco_512x512
  Results:
  - Dataset: COCO
    Metrics:
      AP: 0.613
      AP@0.5: 0.833
      AP@0.75: 0.667
      AR: 0.659
      AR@0.5: 0.85
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/bottom_up/hourglass_ae/hourglass_ae_coco_512x512-90af499f_20210920.pth
- Config: configs/body/2d_kpt_sview_rgb_img/associative_embedding/coco/hourglass_ae_coco_512x512.py
  In Collection: Associative Embedding
  Metadata:
    Architecture: *id001
    Training Data: COCO
  Name: associative_embedding_hourglass_ae_coco_512x512
  Results:
  - Dataset: COCO
    Metrics:
      AP: 0.667
      AP@0.5: 0.855
      AP@0.75: 0.723
      AR: 0.707
      AR@0.5: 0.877
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/bottom_up/hourglass_ae/hourglass_ae_coco_512x512-90af499f_20210920.pth
