Collections:
- Name: HRNet
  Paper:
    Title: Deep high-resolution representation learning for human pose estimation
    URL: http://openaccess.thecvf.com/content_CVPR_2019/html/Sun_Deep_High-Resolution_Representation_Learning_for_Human_Pose_Estimation_CVPR_2019_paper.html
  README: https://github.com/open-mmlab/mmpose/blob/master/docs/en/papers/backbones/hrnet.md
Models:
- Config: configs/body/2d_kpt_sview_rgb_img/associative_embedding/coco/hrnet_w32_coco_512x512.py
  In Collection: HRNet
  Metadata:
    Architecture: &id001
    - Associative Embedding
    - HRNet
    Training Data: COCO
  Name: associative_embedding_hrnet_w32_coco_512x512
  Results:
  - Dataset: COCO
    Metrics:
      AP: 0.654
      AP@0.5: 0.863
      AP@0.75: 0.72
      AR: 0.71
      AR@0.5: 0.892
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/bottom_up/hrnet_w32_coco_512x512-bcb8c247_20200816.pth
- Config: configs/body/2d_kpt_sview_rgb_img/associative_embedding/coco/hrnet_w48_coco_512x512.py
  In Collection: HRNet
  Metadata:
    Architecture: *id001
    Training Data: COCO
  Name: associative_embedding_hrnet_w48_coco_512x512
  Results:
  - Dataset: COCO
    Metrics:
      AP: 0.665
      AP@0.5: 0.86
      AP@0.75: 0.727
      AR: 0.716
      AR@0.5: 0.889
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/bottom_up/hrnet_w48_coco_512x512-cf72fcdf_20200816.pth
- Config: configs/body/2d_kpt_sview_rgb_img/associative_embedding/coco/hrnet_w32_coco_512x512.py
  In Collection: HRNet
  Metadata:
    Architecture: *id001
    Training Data: COCO
  Name: associative_embedding_hrnet_w32_coco_512x512
  Results:
  - Dataset: COCO
    Metrics:
      AP: 0.698
      AP@0.5: 0.877
      AP@0.75: 0.76
      AR: 0.748
      AR@0.5: 0.907
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/bottom_up/hrnet_w32_coco_512x512-bcb8c247_20200816.pth
- Config: configs/body/2d_kpt_sview_rgb_img/associative_embedding/coco/hrnet_w48_coco_512x512.py
  In Collection: HRNet
  Metadata:
    Architecture: *id001
    Training Data: COCO
  Name: associative_embedding_hrnet_w48_coco_512x512
  Results:
  - Dataset: COCO
    Metrics:
      AP: 0.712
      AP@0.5: 0.88
      AP@0.75: 0.771
      AR: 0.757
      AR@0.5: 0.909
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/bottom_up/hrnet_w48_coco_512x512-cf72fcdf_20200816.pth
