Collections:
- Name: UDP
  Paper:
    Title: 'The Devil Is in the Details: Delving Into Unbiased Data Processing for
      Human Pose Estimation'
    URL: http://openaccess.thecvf.com/content_CVPR_2020/html/Huang_The_Devil_Is_in_the_Details_Delving_Into_Unbiased_Data_CVPR_2020_paper.html
  README: https://github.com/open-mmlab/mmpose/blob/master/docs/en/papers/techniques/udp.md
Models:
- Config: configs/body/2d_kpt_sview_rgb_img/associative_embedding/coco/hrnet_w32_coco_512x512_udp.py
  In Collection: UDP
  Metadata:
    Architecture: &id001
    - Associative Embedding
    - HRNet
    - UDP
    Training Data: COCO
  Name: associative_embedding_hrnet_w32_coco_512x512_udp
  Results:
  - Dataset: COCO
    Metrics:
      AP: 0.671
      AP@0.5: 0.863
      AP@0.75: 0.729
      AR: 0.717
      AR@0.5: 0.889
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/bottom_up/hrnet_w32_coco_512x512_udp-91663bf9_20210220.pth
- Config: configs/body/2d_kpt_sview_rgb_img/associative_embedding/coco/hrnet_w48_coco_512x512_udp.py
  In Collection: UDP
  Metadata:
    Architecture: *id001
    Training Data: COCO
  Name: associative_embedding_hrnet_w48_coco_512x512_udp
  Results:
  - Dataset: COCO
    Metrics:
      AP: 0.681
      AP@0.5: 0.872
      AP@0.75: 0.741
      AR: 0.725
      AR@0.5: 0.892
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/bottom_up/hrnet_w48_coco_512x512_udp-de08fd8c_20210222.pth
