name: moments_cvpr
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pytorch::pytorch=1.11.0
  - pytorch::torchvision=0.12.0
  - pytorch::torchaudio=0.11.0
  - conda-forge::ffmpeg
  - pip
  - pip:
    - git+https://github.com/facebookresearch/pytorchvideo.git
