Collections:
- Name: SimpleBaseline2D
  Paper:
    Title: Simple baselines for human pose estimation and tracking
    URL: http://openaccess.thecvf.com/content_ECCV_2018/html/Bin_Xiao_Simple_Baselines_for_ECCV_2018_paper.html
  README: https://github.com/open-mmlab/mmpose/blob/master/docs/en/papers/algorithms/simplebaseline2d.md
Models:
- Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/crowdpose/res50_crowdpose_256x192.py
  In Collection: SimpleBaseline2D
  Metadata:
    Architecture: &id001
    - SimpleBaseline2D
    - ResNet
    Training Data: CrowdPose
  Name: topdown_heatmap_res50_crowdpose_256x192
  Results:
  - Dataset: CrowdPose
    Metrics:
      AP: 0.637
      AP (E): 0.739
      AP (H): 0.506
      AP (M): 0.65
      AP@0.5: 0.808
      AP@0.75: 0.692
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/resnet/res50_crowdpose_256x192-c6a526b6_20201227.pth
- Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/crowdpose/res101_crowdpose_256x192.py
  In Collection: SimpleBaseline2D
  Metadata:
    Architecture: *id001
    Training Data: CrowdPose
  Name: topdown_heatmap_res101_crowdpose_256x192
  Results:
  - Dataset: CrowdPose
    Metrics:
      AP: 0.647
      AP (E): 0.744
      AP (H): 0.522
      AP (M): 0.658
      AP@0.5: 0.81
      AP@0.75: 0.703
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/resnet/res101_crowdpose_256x192-8f5870f4_20201227.pth
- Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/crowdpose/res101_crowdpose_320x256.py
  In Collection: SimpleBaseline2D
  Metadata:
    Architecture: *id001
    Training Data: CrowdPose
  Name: topdown_heatmap_res101_crowdpose_320x256
  Results:
  - Dataset: CrowdPose
    Metrics:
      AP: 0.661
      AP (E): 0.759
      AP (H): 0.536
      AP (M): 0.671
      AP@0.5: 0.821
      AP@0.75: 0.714
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/resnet/res101_crowdpose_320x256-c88c512a_20201227.pth
- Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/crowdpose/res152_crowdpose_256x192.py
  In Collection: SimpleBaseline2D
  Metadata:
    Architecture: *id001
    Training Data: CrowdPose
  Name: topdown_heatmap_res152_crowdpose_256x192
  Results:
  - Dataset: CrowdPose
    Metrics:
      AP: 0.656
      AP (E): 0.754
      AP (H): 0.532
      AP (M): 0.666
      AP@0.5: 0.818
      AP@0.75: 0.712
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/resnet/res152_crowdpose_256x192-dbd49aba_20201227.pth
