Collections:
- Name: ResNet
  Paper:
    Title: Deep residual learning for image recognition
    URL: http://openaccess.thecvf.com/content_cvpr_2016/html/He_Deep_Residual_Learning_CVPR_2016_paper.html
  README: https://github.com/open-mmlab/mmpose/blob/master/docs/en/papers/backbones/resnet.md
Models:
- Config: configs/body/2d_kpt_sview_rgb_img/deeppose/coco/res50_coco_256x192.py
  In Collection: ResNet
  Metadata:
    Architecture: &id001
    - DeepPose
    - ResNet
    Training Data: COCO
  Name: deeppose_res50_coco_256x192
  Results:
  - Dataset: COCO
    Metrics:
      AP: 0.526
      AP@0.5: 0.816
      AP@0.75: 0.586
      AR: 0.638
      AR@0.5: 0.887
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/deeppose/deeppose_res50_coco_256x192-f6de6c0e_20210205.pth
- Config: configs/body/2d_kpt_sview_rgb_img/deeppose/coco/res101_coco_256x192.py
  In Collection: ResNet
  Metadata:
    Architecture: *id001
    Training Data: COCO
  Name: deeppose_res101_coco_256x192
  Results:
  - Dataset: COCO
    Metrics:
      AP: 0.56
      AP@0.5: 0.832
      AP@0.75: 0.628
      AR: 0.668
      AR@0.5: 0.9
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/deeppose/deeppose_res101_coco_256x192-2f247111_20210205.pth
- Config: configs/body/2d_kpt_sview_rgb_img/deeppose/coco/res152_coco_256x192.py
  In Collection: ResNet
  Metadata:
    Architecture: *id001
    Training Data: COCO
  Name: deeppose_res152_coco_256x192
  Results:
  - Dataset: COCO
    Metrics:
      AP: 0.583
      AP@0.5: 0.843
      AP@0.75: 0.659
      AR: 0.686
      AR@0.5: 0.907
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/deeppose/deeppose_res152_coco_256x192-7df89a88_20210205.pth
