Collections:
- Name: HRNet
  Paper:
    Title: Deep high-resolution representation learning for human pose estimation
    URL: http://openaccess.thecvf.com/content_CVPR_2019/html/Sun_Deep_High-Resolution_Representation_Learning_for_Human_Pose_Estimation_CVPR_2019_paper.html
  README: https://github.com/open-mmlab/mmpose/blob/master/docs/en/papers/backbones/hrnet.md
Models:
- Config: configs/body/2d_kpt_sview_rgb_img/associative_embedding/coco/hrnet_w48_mhp_512x512.py
  In Collection: HRNet
  Metadata:
    Architecture: &id001
    - Associative Embedding
    - HRNet
    Training Data: MHP
  Name: associative_embedding_hrnet_w48_mhp_512x512
  Results:
  - Dataset: MHP
    Metrics:
      AP: 0.583
      AP@0.5: 0.895
      AP@0.75: 0.666
      AR: 0.656
      AR@0.5: 0.931
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/bottom_up/hrnet_w48_mhp_512x512-85a6ab6f_20201229.pth
- Config: configs/body/2d_kpt_sview_rgb_img/associative_embedding/coco/hrnet_w48_mhp_512x512.py
  In Collection: HRNet
  Metadata:
    Architecture: *id001
    Training Data: MHP
  Name: associative_embedding_hrnet_w48_mhp_512x512
  Results:
  - Dataset: MHP
    Metrics:
      AP: 0.592
      AP@0.5: 0.898
      AP@0.75: 0.673
      AR: 0.664
      AR@0.5: 0.932
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/bottom_up/hrnet_w48_mhp_512x512-85a6ab6f_20201229.pth
