Collections:
- Name: Hourglass
  Paper:
    Title: Stacked hourglass networks for human pose estimation
    URL: https://link.springer.com/chapter/10.1007/978-3-319-46484-8_29
  README: https://github.com/open-mmlab/mmpose/blob/master/docs/en/papers/backbones/hourglass.md
Models:
- Config: configs/face/2d_kpt_sview_rgb_img/topdown_heatmap/coco_wholebody_face/hourglass52_coco_wholebody_face_256x256.py
  In Collection: Hourglass
  Metadata:
    Architecture:
    - Hourglass
    Training Data: COCO-WholeBody-Face
  Name: topdown_heatmap_hourglass52_coco_wholebody_face_256x256
  Results:
  - Dataset: COCO-WholeBody-Face
    Metrics:
      NME: 0.0586
    Task: Face 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/face/hourglass/hourglass52_coco_wholebody_face_256x256-6994cf2e_20210909.pth
