Collections:
- Name: DarkPose
  Paper:
    Title: Distribution-aware coordinate representation for human pose estimation
    URL: http://openaccess.thecvf.com/content_CVPR_2020/html/Zhang_Distribution-Aware_Coordinate_Representation_for_Human_Pose_Estimation_CVPR_2020_paper.html
  README: https://github.com/open-mmlab/mmpose/blob/master/docs/en/papers/techniques/dark.md
Models:
- Config: configs/face/2d_kpt_sview_rgb_img/topdown_heatmap/coco_wholebody_face/hrnetv2_w18_coco_wholebody_face_256x256_dark.py
  In Collection: DarkPose
  Metadata:
    Architecture:
    - HRNetv2
    - DarkPose
    Training Data: COCO-WholeBody-Face
  Name: topdown_heatmap_hrnetv2_w18_coco_wholebody_face_256x256_dark
  Results:
  - Dataset: COCO-WholeBody-Face
    Metrics:
      NME: 0.0513
    Task: Face 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/face/darkpose/hrnetv2_w18_coco_wholebody_face_256x256_dark-3d9a334e_20210909.pth
