Collections:
- Name: MobilenetV2
  Paper:
    Title: 'Mobilenetv2: Inverted residuals and linear bottlenecks'
    URL: http://openaccess.thecvf.com/content_cvpr_2018/html/Sandler_MobileNetV2_Inverted_Residuals_CVPR_2018_paper.html
  README: https://github.com/open-mmlab/mmpose/blob/master/docs/en/papers/backbones/mobilenetv2.md
Models:
- Config: configs/face/2d_kpt_sview_rgb_img/topdown_heatmap/coco_wholebody_face/mobilenetv2_coco_wholebody_face_256x256.py
  In Collection: MobilenetV2
  Metadata:
    Architecture:
    - MobilenetV2
    Training Data: COCO-WholeBody-Face
  Name: topdown_heatmap_mobilenetv2_coco_wholebody_face_256x256
  Results:
  - Dataset: COCO-WholeBody-Face
    Metrics:
      NME: 0.0612
    Task: Face 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/face/mobilenetv2/mobilenetv2_coco_wholebody_face_256x256-4a3f096e_20210909.pth
