Collections:
- Name: HRNet
  Paper:
    Title: Deep high-resolution representation learning for human pose estimation
    URL: http://openaccess.thecvf.com/content_CVPR_2019/html/Sun_Deep_High-Resolution_Representation_Learning_for_Human_Pose_Estimation_CVPR_2019_paper.html
  README: https://github.com/open-mmlab/mmpose/blob/master/docs/en/papers/backbones/hrnet.md
Models:
- Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/ochuman/hrnet_w32_ochuman_256x192.py
  In Collection: HRNet
  Metadata:
    Architecture: &id001
    - HRNet
    Training Data: OCHuman
  Name: topdown_heatmap_hrnet_w32_ochuman_256x192
  Results:
  - Dataset: OCHuman
    Metrics:
      AP: 0.591
      AP@0.5: 0.748
      AP@0.75: 0.641
      AR: 0.631
      AR@0.5: 0.775
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/hrnet/hrnet_w32_coco_256x192-c78dce93_20200708.pth
- Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/ochuman/hrnet_w32_ochuman_384x288.py
  In Collection: HRNet
  Metadata:
    Architecture: *id001
    Training Data: OCHuman
  Name: topdown_heatmap_hrnet_w32_ochuman_384x288
  Results:
  - Dataset: OCHuman
    Metrics:
      AP: 0.606
      AP@0.5: 0.748
      AP@0.75: 0.65
      AR: 0.647
      AR@0.5: 0.776
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/hrnet/hrnet_w32_coco_384x288-d9f0d786_20200708.pth
- Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/ochuman/hrnet_w48_ochuman_256x192.py
  In Collection: HRNet
  Metadata:
    Architecture: *id001
    Training Data: OCHuman
  Name: topdown_heatmap_hrnet_w48_ochuman_256x192
  Results:
  - Dataset: OCHuman
    Metrics:
      AP: 0.611
      AP@0.5: 0.752
      AP@0.75: 0.663
      AR: 0.648
      AR@0.5: 0.778
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/hrnet/hrnet_w48_coco_256x192-b9e0b3ab_20200708.pth
- Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/ochuman/hrnet_w48_ochuman_384x288.py
  In Collection: HRNet
  Metadata:
    Architecture: *id001
    Training Data: OCHuman
  Name: topdown_heatmap_hrnet_w48_ochuman_384x288
  Results:
  - Dataset: OCHuman
    Metrics:
      AP: 0.616
      AP@0.5: 0.749
      AP@0.75: 0.663
      AR: 0.653
      AR@0.5: 0.773
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/hrnet/hrnet_w48_coco_384x288-314c8528_20200708.pth
