Collections:
- Name: SimpleBaseline2D
  Paper:
    Title: Simple baselines for human pose estimation and tracking
    URL: http://openaccess.thecvf.com/content_ECCV_2018/html/Bin_Xiao_Simple_Baselines_for_ECCV_2018_paper.html
  README: https://github.com/open-mmlab/mmpose/blob/master/docs/en/papers/algorithms/simplebaseline2d.md
Models:
- Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/res50_coco_256x192.py
  In Collection: SimpleBaseline2D
  Metadata:
    Architecture: &id001
    - SimpleBaseline2D
    - ResNet
    Training Data: OCHuman
  Name: topdown_heatmap_res50_coco_256x192
  Results:
  - Dataset: OCHuman
    Metrics:
      AP: 0.546
      AP@0.5: 0.726
      AP@0.75: 0.593
      AR: 0.592
      AR@0.5: 0.755
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/resnet/res50_coco_256x192-ec54d7f3_20200709.pth
- Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/res50_coco_384x288.py
  In Collection: SimpleBaseline2D
  Metadata:
    Architecture: *id001
    Training Data: OCHuman
  Name: topdown_heatmap_res50_coco_384x288
  Results:
  - Dataset: OCHuman
    Metrics:
      AP: 0.539
      AP@0.5: 0.723
      AP@0.75: 0.574
      AR: 0.588
      AR@0.5: 0.756
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/resnet/res50_coco_384x288-e6f795e9_20200709.pth
- Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/res101_coco_256x192.py
  In Collection: SimpleBaseline2D
  Metadata:
    Architecture: *id001
    Training Data: OCHuman
  Name: topdown_heatmap_res101_coco_256x192
  Results:
  - Dataset: OCHuman
    Metrics:
      AP: 0.559
      AP@0.5: 0.724
      AP@0.75: 0.606
      AR: 0.605
      AR@0.5: 0.751
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/resnet/res101_coco_256x192-6e6babf0_20200708.pth
- Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/res101_coco_384x288.py
  In Collection: SimpleBaseline2D
  Metadata:
    Architecture: *id001
    Training Data: OCHuman
  Name: topdown_heatmap_res101_coco_384x288
  Results:
  - Dataset: OCHuman
    Metrics:
      AP: 0.571
      AP@0.5: 0.715
      AP@0.75: 0.615
      AR: 0.615
      AR@0.5: 0.748
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/resnet/res101_coco_384x288-8c71bdc9_20200709.pth
- Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/res152_coco_256x192.py
  In Collection: SimpleBaseline2D
  Metadata:
    Architecture: *id001
    Training Data: OCHuman
  Name: topdown_heatmap_res152_coco_256x192
  Results:
  - Dataset: OCHuman
    Metrics:
      AP: 0.57
      AP@0.5: 0.725
      AP@0.75: 0.617
      AR: 0.616
      AR@0.5: 0.754
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/resnet/res152_coco_256x192-f6e307c2_20200709.pth
- Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/res152_coco_384x288.py
  In Collection: SimpleBaseline2D
  Metadata:
    Architecture: *id001
    Training Data: OCHuman
  Name: topdown_heatmap_res152_coco_384x288
  Results:
  - Dataset: OCHuman
    Metrics:
      AP: 0.582
      AP@0.5: 0.723
      AP@0.75: 0.627
      AR: 0.627
      AR@0.5: 0.752
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/resnet/res152_coco_384x288-3860d4c9_20200709.pth
