Collections:
- Name: HRNet
  Paper:
    Title: Deep high-resolution representation learning for human pose estimation
    URL: http://openaccess.thecvf.com/content_CVPR_2019/html/Sun_Deep_High-Resolution_Representation_Learning_for_Human_Pose_Estimation_CVPR_2019_paper.html
  README: https://github.com/open-mmlab/mmpose/blob/master/docs/en/papers/backbones/hrnet.md
Models:
- Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/posetrack18/hrnet_w32_posetrack18_256x192.py
  In Collection: HRNet
  Metadata:
    Architecture: &id001
    - HRNet
    Training Data: PoseTrack18
  Name: topdown_heatmap_hrnet_w32_posetrack18_256x192
  Results:
  - Dataset: PoseTrack18
    Metrics:
      Ankl: 78.8
      Elb: 84.3
      Head: 87.4
      Hip: 79.7
      Knee: 81.8
      Shou: 88.6
      Total: 83.0
      Wri: 78.5
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/hrnet/hrnet_w32_posetrack18_256x192-1ee951c4_20201028.pth
- Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/posetrack18/hrnet_w32_posetrack18_384x288.py
  In Collection: HRNet
  Metadata:
    Architecture: *id001
    Training Data: PoseTrack18
  Name: topdown_heatmap_hrnet_w32_posetrack18_384x288
  Results:
  - Dataset: PoseTrack18
    Metrics:
      Ankl: 79.4
      Elb: 85.0
      Head: 87.0
      Hip: 80.5
      Knee: 82.6
      Shou: 88.8
      Total: 83.6
      Wri: 80.1
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/hrnet/hrnet_w32_posetrack18_384x288-806f00a3_20211130.pth
- Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/posetrack18/hrnet_w48_posetrack18_256x192.py
  In Collection: HRNet
  Metadata:
    Architecture: *id001
    Training Data: PoseTrack18
  Name: topdown_heatmap_hrnet_w48_posetrack18_256x192
  Results:
  - Dataset: PoseTrack18
    Metrics:
      Ankl: 80.3
      Elb: 85.8
      Head: 88.2
      Hip: 80.7
      Knee: 83.3
      Shou: 90.1
      Total: 84.4
      Wri: 80.8
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/hrnet/hrnet_w48_posetrack18_256x192-b5d9b3f1_20211130.pth
- Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/posetrack18/hrnet_w48_posetrack18_384x288.py
  In Collection: HRNet
  Metadata:
    Architecture: *id001
    Training Data: PoseTrack18
  Name: topdown_heatmap_hrnet_w48_posetrack18_384x288
  Results:
  - Dataset: PoseTrack18
    Metrics:
      Ankl: 80.9
      Elb: 85.9
      Head: 87.8
      Hip: 81.1
      Knee: 83.3
      Shou: 90.0
      Total: 84.5
      Wri: 81.3
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/hrnet/hrnet_w48_posetrack18_384x288-5fd6d3ff_20211130.pth
- Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/posetrack18/hrnet_w32_posetrack18_256x192.py
  In Collection: HRNet
  Metadata:
    Architecture: *id001
    Training Data: PoseTrack18
  Name: topdown_heatmap_hrnet_w32_posetrack18_256x192
  Results:
  - Dataset: PoseTrack18
    Metrics:
      Ankl: 70.2
      Elb: 79.5
      Head: 78.0
      Hip: 76.9
      Knee: 76.6
      Shou: 82.9
      Total: 76.9
      Wri: 73.8
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/hrnet/hrnet_w32_posetrack18_256x192-1ee951c4_20201028.pth
- Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/posetrack18/hrnet_w32_posetrack18_384x288.py
  In Collection: HRNet
  Metadata:
    Architecture: *id001
    Training Data: PoseTrack18
  Name: topdown_heatmap_hrnet_w32_posetrack18_384x288
  Results:
  - Dataset: PoseTrack18
    Metrics:
      Ankl: 70.5
      Elb: 80.4
      Head: 79.9
      Hip: 74.8
      Knee: 76.1
      Shou: 83.6
      Total: 77.3
      Wri: 74.5
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/hrnet/hrnet_w32_posetrack18_384x288-806f00a3_20211130.pth
- Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/posetrack18/hrnet_w48_posetrack18_256x192.py
  In Collection: HRNet
  Metadata:
    Architecture: *id001
    Training Data: PoseTrack18
  Name: topdown_heatmap_hrnet_w48_posetrack18_256x192
  Results:
  - Dataset: PoseTrack18
    Metrics:
      Ankl: 70.4
      Elb: 80.6
      Head: 80.1
      Hip: 74.3
      Knee: 76.8
      Shou: 83.4
      Total: 77.4
      Wri: 74.8
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/hrnet/hrnet_w48_posetrack18_256x192-b5d9b3f1_20211130.pth
- Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/posetrack18/hrnet_w48_posetrack18_384x288.py
  In Collection: HRNet
  Metadata:
    Architecture: *id001
    Training Data: PoseTrack18
  Name: topdown_heatmap_hrnet_w48_posetrack18_384x288
  Results:
  - Dataset: PoseTrack18
    Metrics:
      Ankl: 71.7
      Elb: 80.9
      Head: 80.2
      Hip: 74.7
      Knee: 76.7
      Shou: 83.8
      Total: 77.8
      Wri: 75.2
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/hrnet/hrnet_w48_posetrack18_384x288-5fd6d3ff_20211130.pth
