Collections:
- Name: HigherHRNet
  Paper:
    Title: 'HigherHRNet: Scale-Aware Representation Learning for Bottom-Up Human Pose
      Estimation'
    URL: http://openaccess.thecvf.com/content_CVPR_2020/html/Cheng_HigherHRNet_Scale-Aware_Representation_Learning_for_Bottom-Up_Human_Pose_Estimation_CVPR_2020_paper.html
  README: https://github.com/open-mmlab/mmpose/blob/master/docs/en/papers/backbones/higherhrnet.md
Models:
- Config: configs/wholebody/2d_kpt_sview_rgb_img/associative_embedding/coco-wholebody/higherhrnet_w32_coco_wholebody_512x512.py
  In Collection: HigherHRNet
  Metadata:
    Architecture: &id001
    - Associative Embedding
    - HigherHRNet
    Training Data: COCO-WholeBody
  Name: associative_embedding_higherhrnet_w32_coco_wholebody_512x512
  Results:
  - Dataset: COCO-WholeBody
    Metrics:
      Body AP: 0.59
      Body AR: 0.672
      Face AP: 0.676
      Face AR: 0.721
      Foot AP: 0.185
      Foot AR: 0.335
      Hand AP: 0.212
      Hand AR: 0.298
      Whole AP: 0.401
      Whole AR: 0.493
    Task: Wholebody 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/bottom_up/higher_hrnet32_coco_wholebody_512x512_plus-2fa137ab_20210517.pth
- Config: configs/wholebody/2d_kpt_sview_rgb_img/associative_embedding/coco-wholebody/higherhrnet_w48_coco_wholebody_512x512.py
  In Collection: HigherHRNet
  Metadata:
    Architecture: *id001
    Training Data: COCO-WholeBody
  Name: associative_embedding_higherhrnet_w48_coco_wholebody_512x512
  Results:
  - Dataset: COCO-WholeBody
    Metrics:
      Body AP: 0.63
      Body AR: 0.706
      Face AP: 0.73
      Face AR: 0.777
      Foot AP: 0.44
      Foot AR: 0.573
      Hand AP: 0.389
      Hand AR: 0.477
      Whole AP: 0.487
      Whole AR: 0.574
    Task: Wholebody 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/bottom_up/higher_hrnet48_coco_wholebody_512x512_plus-934f08aa_20210517.pth
