Collections:
- Name: HRNet
  Paper:
    Title: Deep high-resolution representation learning for human pose estimation
    URL: http://openaccess.thecvf.com/content_CVPR_2019/html/Sun_Deep_High-Resolution_Representation_Learning_for_Human_Pose_Estimation_CVPR_2019_paper.html
  README: https://github.com/open-mmlab/mmpose/blob/master/docs/en/papers/backbones/hrnet.md
Models:
- Config: configs/wholebody/2d_kpt_sview_rgb_img/associative_embedding/coco-wholebody/hrnet_w32_coco_wholebody_512x512.py
  In Collection: HRNet
  Metadata:
    Architecture: &id001
    - Associative Embedding
    - HRNet
    Training Data: COCO-WholeBody
  Name: associative_embedding_hrnet_w32_coco_wholebody_512x512
  Results:
  - Dataset: COCO-WholeBody
    Metrics:
      Body AP: 0.551
      Body AR: 0.65
      Face AP: 0.564
      Face AR: 0.618
      Foot AP: 0.271
      Foot AR: 0.451
      Hand AP: 0.159
      Hand AR: 0.238
      Whole AP: 0.342
      Whole AR: 0.453
    Task: Wholebody 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/bottom_up/hrnet_w32_coco_wholebody_512x512_plus-f1f1185c_20210517.pth
- Config: configs/wholebody/2d_kpt_sview_rgb_img/associative_embedding/coco-wholebody/hrnet_w48_coco_wholebody_512x512.py
  In Collection: HRNet
  Metadata:
    Architecture: *id001
    Training Data: COCO-WholeBody
  Name: associative_embedding_hrnet_w48_coco_wholebody_512x512
  Results:
  - Dataset: COCO-WholeBody
    Metrics:
      Body AP: 0.592
      Body AR: 0.686
      Face AP: 0.619
      Face AR: 0.674
      Foot AP: 0.443
      Foot AR: 0.595
      Hand AP: 0.347
      Hand AR: 0.438
      Whole AP: 0.422
      Whole AR: 0.532
    Task: Wholebody 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/bottom_up/hrnet_w48_coco_wholebody_512x512_plus-4de8a695_20210517.pth
