Collections:
- Name: HRNetv2
  Paper:
    Title: Deep High-Resolution Representation Learning for Visual Recognition
    URL: https://ieeexplore.ieee.org/abstract/document/9052469/
  README: https://github.com/open-mmlab/mmpose/blob/master/docs/en/papers/backbones/hrnetv2.md
Models:
- Config: configs/hand/2d_kpt_sview_rgb_img/topdown_heatmap/panoptic2d/hrnetv2_w18_panoptic_256x256.py
  In Collection: HRNetv2
  Metadata:
    Architecture:
    - HRNetv2
    Training Data: CMU Panoptic HandDB
  Name: topdown_heatmap_hrnetv2_w18_panoptic_256x256
  Results:
  - Dataset: CMU Panoptic HandDB
    Metrics:
      AUC: 0.744
      EPE: 7.79
      PCKh@0.7: 0.999
    Task: Hand 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/hand/hrnetv2/hrnetv2_w18_panoptic_256x256-53b12345_20210330.pth
