Collections:
- Name: MobilenetV2
  Paper:
    Title: 'Mobilenetv2: Inverted residuals and linear bottlenecks'
    URL: http://openaccess.thecvf.com/content_cvpr_2018/html/Sandler_MobileNetV2_Inverted_Residuals_CVPR_2018_paper.html
  README: https://github.com/open-mmlab/mmpose/blob/master/docs/en/papers/backbones/mobilenetv2.md
Models:
- Config: configs/hand/2d_kpt_sview_rgb_img/topdown_heatmap/panoptic2d/mobilenetv2_panoptic_256x256.py
  In Collection: MobilenetV2
  Metadata:
    Architecture:
    - MobilenetV2
    Training Data: CMU Panoptic HandDB
  Name: topdown_heatmap_mobilenetv2_panoptic_256x256
  Results:
  - Dataset: CMU Panoptic HandDB
    Metrics:
      AUC: 0.694
      EPE: 9.7
      PCKh@0.7: 0.998
    Task: Hand 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/hand/mobilenetv2/mobilenetv2_panoptic_256x256-b733d98c_20210330.pth
