input_config:
  metadata_path: "/checkpoint/miguelmartin/ego4d_data/ego4d.json"
  feature_path: "/checkpoint/miguelmartin/ego4d_track2_features/full_scale/omnivore_video_swinL"
  feature_extract_config_path: "/private/home/miguelmartin/ego4d/ego4d_public/ego4d/features/configs/omnivore_video.yaml"
  features_per_second: 1.875
  narration_width_sample_sec: 0.1
  max_num_feature_vec_video_uids: 30
  dsets_to_use: [ego4d]
model_config:
  model_name: "vit_huge_mae_pretraining"
batch_size: 128
num_workers: 10
prefetch_factor: 4
num_epochs: 1600
accelerator: "gpu"
devices: 1
run_locally: false
tb_log_dir: "/private/home/miguelmartin/ego4d/ego4d_public/runs"
tb_log_name: "clep"
lr: 0.001
beta1: 0.9
beta2: 0.98
wd: 0.1
eps: 1.0e-6
eval_per_iter: 500
eval_init: true
checkpoint_dir: "/checkpoint/miguelmartin/mae/checkpoints"
