Collections:
- Name: ResNet
  Paper:
    Title: Deep residual learning for image recognition
    URL: http://openaccess.thecvf.com/content_cvpr_2016/html/He_Deep_Residual_Learning_CVPR_2016_paper.html
  README: https://github.com/open-mmlab/mmpose/blob/master/docs/en/papers/backbones/resnet.md
Models:
- Config: configs/face/2d_kpt_sview_rgb_img/deeppose/wflw/res50_wflw_256x256.py
  In Collection: ResNet
  Metadata:
    Architecture:
    - DeepPose
    - ResNet
    Training Data: WFLW
  Name: deeppose_res50_wflw_256x256
  Results:
  - Dataset: WFLW
    Metrics:
      NME blur: 5.45
      NME expression: 5.2
      NME illumination: 4.81
      NME makeup: 4.82
      NME occlusion: 5.69
      NME pose: 8.5
      NME test: 4.85
    Task: Face 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/face/deeppose/deeppose_res50_wflw_256x256-92d0ba7f_20210303.pth
