Collections:
- Name: HRNetv2
  Paper:
    Title: Deep High-Resolution Representation Learning for Visual Recognition
    URL: https://ieeexplore.ieee.org/abstract/document/9052469/
  README: https://github.com/open-mmlab/mmpose/blob/master/docs/en/papers/backbones/hrnetv2.md
Models:
- Config: configs/face/2d_kpt_sview_rgb_img/topdown_heatmap/wflw/hrnetv2_w18_wflw_256x256_awing.py
  In Collection: HRNetv2
  Metadata:
    Architecture:
    - HRNetv2
    - AdaptiveWingloss
    Training Data: WFLW
  Name: topdown_heatmap_hrnetv2_w18_wflw_256x256_awing
  Results:
  - Dataset: WFLW
    Metrics:
      NME blur: 4.59
      NME expression: 4.28
      NME illumination: 3.96
      NME makeup: 3.85
      NME occlusion: 4.78
      NME pose: 6.94
      NME test: 4.02
    Task: Face 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/face/hrnetv2/hrnetv2_w18_wflw_256x256_awing-5af5055c_20211212.pth
