Collections:
- Name: SimpleBaseline2D
  Paper:
    Title: Simple baselines for human pose estimation and tracking
    URL: http://openaccess.thecvf.com/content_ECCV_2018/html/Bin_Xiao_Simple_Baselines_for_ECCV_2018_paper.html
  README: https://github.com/open-mmlab/mmpose/blob/master/docs/en/papers/algorithms/simplebaseline2d.md
Models:
- Config: configs/hand/2d_kpt_sview_rgb_img/topdown_heatmap/interhand2d/res50_interhand2d_human_256x256.py
  In Collection: SimpleBaseline2D
  Metadata:
    Architecture: &id001
    - SimpleBaseline2D
    - ResNet
    Training Data: InterHand2.6M
  Name: topdown_heatmap_res50_interhand2d_human_256x256
  Results:
  - Dataset: InterHand2.6M
    Metrics:
      AUC: 0.828
      EPE: 5.15
      PCK@0.2: 0.973
    Task: Hand 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/hand/resnet/res50_interhand2d_256x256_human-77b27d1a_20201029.pth
- Config: configs/hand/2d_kpt_sview_rgb_img/topdown_heatmap/interhand2d/res50_interhand2d_human_256x256.py
  In Collection: SimpleBaseline2D
  Metadata:
    Architecture: *id001
    Training Data: InterHand2.6M
  Name: topdown_heatmap_res50_interhand2d_human_256x256
  Results:
  - Dataset: InterHand2.6M
    Metrics:
      AUC: 0.826
      EPE: 5.27
      PCK@0.2: 0.973
    Task: Hand 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/hand/resnet/res50_interhand2d_256x256_human-77b27d1a_20201029.pth
- Config: configs/hand/2d_kpt_sview_rgb_img/topdown_heatmap/interhand2d/res50_interhand2d_human_256x256.py
  In Collection: SimpleBaseline2D
  Metadata:
    Architecture: *id001
    Training Data: InterHand2.6M
  Name: topdown_heatmap_res50_interhand2d_human_256x256
  Results:
  - Dataset: InterHand2.6M
    Metrics:
      AUC: 0.841
      EPE: 4.9
      PCK@0.2: 0.975
    Task: Hand 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/hand/resnet/res50_interhand2d_256x256_human-77b27d1a_20201029.pth
- Config: configs/hand/2d_kpt_sview_rgb_img/topdown_heatmap/interhand2d/res50_interhand2d_human_256x256.py
  In Collection: SimpleBaseline2D
  Metadata:
    Architecture: *id001
    Training Data: InterHand2.6M
  Name: topdown_heatmap_res50_interhand2d_human_256x256
  Results:
  - Dataset: InterHand2.6M
    Metrics:
      AUC: 0.839
      EPE: 4.97
      PCK@0.2: 0.975
    Task: Hand 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/hand/resnet/res50_interhand2d_256x256_human-77b27d1a_20201029.pth
- Config: configs/hand/2d_kpt_sview_rgb_img/topdown_heatmap/interhand2d/res50_interhand2d_machine_256x256.py
  In Collection: SimpleBaseline2D
  Metadata:
    Architecture: *id001
    Training Data: InterHand2.6M
  Name: topdown_heatmap_res50_interhand2d_machine_256x256
  Results:
  - Dataset: InterHand2.6M
    Metrics:
      AUC: 0.824
      EPE: 5.39
      PCK@0.2: 0.97
    Task: Hand 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/hand/resnet/res50_interhand2d_256x256_machine-8f3efe9a_20201102.pth
- Config: configs/hand/2d_kpt_sview_rgb_img/topdown_heatmap/interhand2d/res50_interhand2d_machine_256x256.py
  In Collection: SimpleBaseline2D
  Metadata:
    Architecture: *id001
    Training Data: InterHand2.6M
  Name: topdown_heatmap_res50_interhand2d_machine_256x256
  Results:
  - Dataset: InterHand2.6M
    Metrics:
      AUC: 0.821
      EPE: 5.52
      PCK@0.2: 0.969
    Task: Hand 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/hand/resnet/res50_interhand2d_256x256_machine-8f3efe9a_20201102.pth
- Config: configs/hand/2d_kpt_sview_rgb_img/topdown_heatmap/interhand2d/res50_interhand2d_machine_256x256.py
  In Collection: SimpleBaseline2D
  Metadata:
    Architecture: *id001
    Training Data: InterHand2.6M
  Name: topdown_heatmap_res50_interhand2d_machine_256x256
  Results:
  - Dataset: InterHand2.6M
    Metrics:
      AUC: 0.838
      EPE: 5.03
      PCK@0.2: 0.972
    Task: Hand 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/hand/resnet/res50_interhand2d_256x256_machine-8f3efe9a_20201102.pth
- Config: configs/hand/2d_kpt_sview_rgb_img/topdown_heatmap/interhand2d/res50_interhand2d_machine_256x256.py
  In Collection: SimpleBaseline2D
  Metadata:
    Architecture: *id001
    Training Data: InterHand2.6M
  Name: topdown_heatmap_res50_interhand2d_machine_256x256
  Results:
  - Dataset: InterHand2.6M
    Metrics:
      AUC: 0.837
      EPE: 5.11
      PCK@0.2: 0.972
    Task: Hand 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/hand/resnet/res50_interhand2d_256x256_machine-8f3efe9a_20201102.pth
- Config: configs/hand/2d_kpt_sview_rgb_img/topdown_heatmap/interhand2d/res50_interhand2d_all_256x256.py
  In Collection: SimpleBaseline2D
  Metadata:
    Architecture: *id001
    Training Data: InterHand2.6M
  Name: topdown_heatmap_res50_interhand2d_all_256x256
  Results:
  - Dataset: InterHand2.6M
    Metrics:
      AUC: 0.84
      EPE: 4.66
      PCK@0.2: 0.977
    Task: Hand 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/hand/resnet/res50_interhand2d_256x256_all-78cc95d4_20201102.pth
- Config: configs/hand/2d_kpt_sview_rgb_img/topdown_heatmap/interhand2d/res50_interhand2d_all_256x256.py
  In Collection: SimpleBaseline2D
  Metadata:
    Architecture: *id001
    Training Data: InterHand2.6M
  Name: topdown_heatmap_res50_interhand2d_all_256x256
  Results:
  - Dataset: InterHand2.6M
    Metrics:
      AUC: 0.839
      EPE: 4.65
      PCK@0.2: 0.979
    Task: Hand 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/hand/resnet/res50_interhand2d_256x256_all-78cc95d4_20201102.pth
- Config: configs/hand/2d_kpt_sview_rgb_img/topdown_heatmap/interhand2d/res50_interhand2d_all_256x256.py
  In Collection: SimpleBaseline2D
  Metadata:
    Architecture: *id001
    Training Data: InterHand2.6M
  Name: topdown_heatmap_res50_interhand2d_all_256x256
  Results:
  - Dataset: InterHand2.6M
    Metrics:
      AUC: 0.838
      EPE: 4.42
      PCK@0.2: 0.979
    Task: Hand 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/hand/resnet/res50_interhand2d_256x256_all-78cc95d4_20201102.pth
- Config: configs/hand/2d_kpt_sview_rgb_img/topdown_heatmap/interhand2d/res50_interhand2d_all_256x256.py
  In Collection: SimpleBaseline2D
  Metadata:
    Architecture: *id001
    Training Data: InterHand2.6M
  Name: topdown_heatmap_res50_interhand2d_all_256x256
  Results:
  - Dataset: InterHand2.6M
    Metrics:
      AUC: 0.851
      EPE: 4.46
      PCK@0.2: 0.979
    Task: Hand 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/hand/resnet/res50_interhand2d_256x256_all-78cc95d4_20201102.pth
