Collections:
- Name: SimpleBaseline2D
  Paper:
    Title: Simple baselines for human pose estimation and tracking
    URL: http://openaccess.thecvf.com/content_ECCV_2018/html/Bin_Xiao_Simple_Baselines_for_ECCV_2018_paper.html
  README: https://github.com/open-mmlab/mmpose/blob/master/docs/en/papers/algorithms/simplebaseline2d.md
Models:
- Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/mpii_trb/res50_mpii_trb_256x256.py
  In Collection: SimpleBaseline2D
  Metadata:
    Architecture: &id001
    - SimpleBaseline2D
    - ResNet
    Training Data: MPII-TRB
  Name: topdown_heatmap_res50_mpii_trb_256x256
  Results:
  - Dataset: MPII-TRB
    Metrics:
      Contour Acc: 0.858
      Mean Acc: 0.868
      Skeleton Acc: 0.887
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/resnet/res50_mpii_trb_256x256-896036b8_20200812.pth
- Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/mpii_trb/res101_mpii_trb_256x256.py
  In Collection: SimpleBaseline2D
  Metadata:
    Architecture: *id001
    Training Data: MPII-TRB
  Name: topdown_heatmap_res101_mpii_trb_256x256
  Results:
  - Dataset: MPII-TRB
    Metrics:
      Contour Acc: 0.863
      Mean Acc: 0.873
      Skeleton Acc: 0.89
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/resnet/res101_mpii_trb_256x256-cfad2f05_20200812.pth
- Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/mpii_trb/res152_mpii_trb_256x256.py
  In Collection: SimpleBaseline2D
  Metadata:
    Architecture: *id001
    Training Data: MPII-TRB
  Name: topdown_heatmap_res152_mpii_trb_256x256
  Results:
  - Dataset: MPII-TRB
    Metrics:
      Contour Acc: 0.868
      Mean Acc: 0.879
      Skeleton Acc: 0.897
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/resnet/res152_mpii_trb_256x256-dd369ce6_20200812.pth
