Collections:
- Name: InterNet
  Paper:
    Title: 'InterHand2.6M: A Dataset and Baseline for 3D Interacting Hand Pose Estimation
      from a Single RGB Image'
    URL: https://link.springer.com/content/pdf/10.1007/978-3-030-58565-5_33.pdf
  README: https://github.com/open-mmlab/mmpose/blob/master/docs/en/papers/algorithms/internet.md
Models:
- Config: configs/hand/3d_kpt_sview_rgb_img/internet/interhand3d/res50_interhand3d_all_256x256.py
  In Collection: InterNet
  Metadata:
    Architecture: &id001
    - InterNet
    - ResNet
    Training Data: InterHand2.6M
  Name: internet_res50_interhand3d_all_256x256
  Results:
  - Dataset: InterHand2.6M
    Metrics:
      APh: 0.99
      MPJPE-all: 11.59
      MPJPE-interacting: 13.4
      MPJPE-single: 9.47
    Task: Hand 3D Keypoint
  Weights: https://download.openmmlab.com/mmpose/hand3d/internet/res50_intehand3dv1.0_all_256x256-42b7f2ac_20210702.pth
- Config: configs/hand/3d_kpt_sview_rgb_img/internet/interhand3d/res50_interhand3d_all_256x256.py
  In Collection: InterNet
  Metadata:
    Architecture: *id001
    Training Data: InterHand2.6M
  Name: internet_res50_interhand3d_all_256x256
  Results:
  - Dataset: InterHand2.6M
    Metrics:
      APh: 0.98
      MPJPE-all: 13.16
      MPJPE-interacting: 15.23
      MPJPE-single: 11.22
    Task: Hand 3D Keypoint
  Weights: https://download.openmmlab.com/mmpose/hand3d/internet/res50_intehand3dv1.0_all_256x256-42b7f2ac_20210702.pth
