Collections:
- Name: AlexNet
  Paper:
    Title: Imagenet classification with deep convolutional neural networks
    URL: https://proceedings.neurips.cc/paper/4824-imagenet-classification-with-deep-convolutional-neural-networks.pdf
  README: https://github.com/open-mmlab/mmpose/blob/master/docs/en/papers/backbones/alexnet.md
Models:
- Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/alexnet_coco_256x192.py
  In Collection: AlexNet
  Metadata:
    Architecture:
    - AlexNet
    Training Data: COCO
  Name: topdown_heatmap_alexnet_coco_256x192
  Results:
  - Dataset: COCO
    Metrics:
      AP: 0.397
      AP@0.5: 0.758
      AP@0.75: 0.381
      AR: 0.478
      AR@0.5: 0.822
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/alexnet/alexnet_coco_256x192-a7b1fd15_20200727.pth
