Collections:
- Name: CPM
  Paper:
    Title: Convolutional pose machines
    URL: http://openaccess.thecvf.com/content_cvpr_2016/html/Wei_Convolutional_Pose_Machines_CVPR_2016_paper.html
  README: https://github.com/open-mmlab/mmpose/blob/master/docs/en/papers/backbones/cpm.md
Models:
- Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/cpm_coco_256x192.py
  In Collection: CPM
  Metadata:
    Architecture: &id001
    - CPM
    Training Data: COCO
  Name: topdown_heatmap_cpm_coco_256x192
  Results:
  - Dataset: COCO
    Metrics:
      AP: 0.623
      AP@0.5: 0.859
      AP@0.75: 0.704
      AR: 0.686
      AR@0.5: 0.903
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/cpm/cpm_coco_256x192-aa4ba095_20200817.pth
- Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/cpm_coco_384x288.py
  In Collection: CPM
  Metadata:
    Architecture: *id001
    Training Data: COCO
  Name: topdown_heatmap_cpm_coco_384x288
  Results:
  - Dataset: COCO
    Metrics:
      AP: 0.65
      AP@0.5: 0.864
      AP@0.75: 0.725
      AR: 0.708
      AR@0.5: 0.905
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/cpm/cpm_coco_384x288-80feb4bc_20200821.pth
