Collections:
- Name: Hourglass
  Paper:
    Title: Stacked hourglass networks for human pose estimation
    URL: https://link.springer.com/chapter/10.1007/978-3-319-46484-8_29
  README: https://github.com/open-mmlab/mmpose/blob/master/docs/en/papers/backbones/hourglass.md
Models:
- Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/hourglass52_coco_256x256.py
  In Collection: Hourglass
  Metadata:
    Architecture: &id001
    - Hourglass
    Training Data: COCO
  Name: topdown_heatmap_hourglass52_coco_256x256
  Results:
  - Dataset: COCO
    Metrics:
      AP: 0.726
      AP@0.5: 0.896
      AP@0.75: 0.799
      AR: 0.78
      AR@0.5: 0.934
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/hourglass/hourglass52_coco_256x256-4ec713ba_20200709.pth
- Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/hourglass52_coco_384x384.py
  In Collection: Hourglass
  Metadata:
    Architecture: *id001
    Training Data: COCO
  Name: topdown_heatmap_hourglass52_coco_384x384
  Results:
  - Dataset: COCO
    Metrics:
      AP: 0.746
      AP@0.5: 0.9
      AP@0.75: 0.813
      AR: 0.797
      AR@0.5: 0.939
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/hourglass/hourglass52_coco_384x384-be91ba2b_20200812.pth
