Collections:
- Name: HRNet
  Paper:
    Title: Deep high-resolution representation learning for human pose estimation
    URL: http://openaccess.thecvf.com/content_CVPR_2019/html/Sun_Deep_High-Resolution_Representation_Learning_for_Human_Pose_Estimation_CVPR_2019_paper.html
  README: https://github.com/open-mmlab/mmpose/blob/master/docs/en/papers/backbones/hrnet.md
Models:
- Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/hrnet_w32_coco_256x192.py
  In Collection: HRNet
  Metadata:
    Architecture: &id001
    - HRNet
    Training Data: COCO
  Name: topdown_heatmap_hrnet_w32_coco_256x192
  Results:
  - Dataset: COCO
    Metrics:
      AP: 0.746
      AP@0.5: 0.904
      AP@0.75: 0.819
      AR: 0.799
      AR@0.5: 0.942
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/hrnet/hrnet_w32_coco_256x192-c78dce93_20200708.pth
- Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/hrnet_w32_coco_384x288.py
  In Collection: HRNet
  Metadata:
    Architecture: *id001
    Training Data: COCO
  Name: topdown_heatmap_hrnet_w32_coco_384x288
  Results:
  - Dataset: COCO
    Metrics:
      AP: 0.76
      AP@0.5: 0.906
      AP@0.75: 0.829
      AR: 0.81
      AR@0.5: 0.943
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/hrnet/hrnet_w32_coco_384x288-d9f0d786_20200708.pth
- Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/hrnet_w48_coco_256x192.py
  In Collection: HRNet
  Metadata:
    Architecture: *id001
    Training Data: COCO
  Name: topdown_heatmap_hrnet_w48_coco_256x192
  Results:
  - Dataset: COCO
    Metrics:
      AP: 0.756
      AP@0.5: 0.907
      AP@0.75: 0.825
      AR: 0.806
      AR@0.5: 0.942
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/hrnet/hrnet_w48_coco_256x192-b9e0b3ab_20200708.pth
- Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/hrnet_w48_coco_384x288.py
  In Collection: HRNet
  Metadata:
    Architecture: *id001
    Training Data: COCO
  Name: topdown_heatmap_hrnet_w48_coco_384x288
  Results:
  - Dataset: COCO
    Metrics:
      AP: 0.767
      AP@0.5: 0.91
      AP@0.75: 0.831
      AR: 0.816
      AR@0.5: 0.946
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/hrnet/hrnet_w48_coco_384x288-314c8528_20200708.pth
