Collections:
- Name: Albumentations
  Paper:
    Title: 'Albumentations: fast and flexible image augmentations'
    URL: https://www.mdpi.com/649002
  README: https://github.com/open-mmlab/mmpose/blob/master/docs/en/papers/techniques/albumentations.md
Models:
- Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/hrnet_w32_coco_256x192_coarsedropout.py
  In Collection: Albumentations
  Metadata:
    Architecture: &id001
    - HRNet
    Training Data: COCO
  Name: topdown_heatmap_hrnet_w32_coco_256x192_coarsedropout
  Results:
  - Dataset: COCO
    Metrics:
      AP: 0.753
      AP@0.5: 0.908
      AP@0.75: 0.822
      AR: 0.806
      AR@0.5: 0.946
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/augmentation/hrnet_w32_coco_256x192_coarsedropout-0f16a0ce_20210320.pth
- Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/hrnet_w32_coco_256x192_gridmask.py
  In Collection: Albumentations
  Metadata:
    Architecture: *id001
    Training Data: COCO
  Name: topdown_heatmap_hrnet_w32_coco_256x192_gridmask
  Results:
  - Dataset: COCO
    Metrics:
      AP: 0.752
      AP@0.5: 0.906
      AP@0.75: 0.825
      AR: 0.804
      AR@0.5: 0.943
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/augmentation/hrnet_w32_coco_256x192_gridmask-868180df_20210320.pth
- Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/hrnet_w32_coco_256x192_photometric.py
  In Collection: Albumentations
  Metadata:
    Architecture: *id001
    Training Data: COCO
  Name: topdown_heatmap_hrnet_w32_coco_256x192_photometric
  Results:
  - Dataset: COCO
    Metrics:
      AP: 0.753
      AP@0.5: 0.909
      AP@0.75: 0.825
      AR: 0.805
      AR@0.5: 0.943
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/augmentation/hrnet_w32_coco_256x192_photometric-308cf591_20210320.pth
