Collections:
- Name: UDP
  Paper:
    Title: 'The Devil Is in the Details: Delving Into Unbiased Data Processing for
      Human Pose Estimation'
    URL: http://openaccess.thecvf.com/content_CVPR_2020/html/Huang_The_Devil_Is_in_the_Details_Delving_Into_Unbiased_Data_CVPR_2020_paper.html
  README: https://github.com/open-mmlab/mmpose/blob/master/docs/en/papers/techniques/udp.md
Models:
- Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/hrnet_w32_coco_256x192_udp.py
  In Collection: UDP
  Metadata:
    Architecture: &id001
    - HRNet
    - UDP
    Training Data: COCO
  Name: topdown_heatmap_hrnet_w32_coco_256x192_udp
  Results:
  - Dataset: COCO
    Metrics:
      AP: 0.76
      AP@0.5: 0.907
      AP@0.75: 0.827
      AR: 0.811
      AR@0.5: 0.945
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/udp/hrnet_w32_coco_256x192_udp-aba0be42_20210220.pth
- Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/hrnet_w32_coco_384x288_udp.py
  In Collection: UDP
  Metadata:
    Architecture: *id001
    Training Data: COCO
  Name: topdown_heatmap_hrnet_w32_coco_384x288_udp
  Results:
  - Dataset: COCO
    Metrics:
      AP: 0.769
      AP@0.5: 0.908
      AP@0.75: 0.833
      AR: 0.817
      AR@0.5: 0.944
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/udp/hrnet_w32_coco_384x288_udp-e97c1a0f_20210223.pth
- Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/hrnet_w48_coco_256x192_udp.py
  In Collection: UDP
  Metadata:
    Architecture: *id001
    Training Data: COCO
  Name: topdown_heatmap_hrnet_w48_coco_256x192_udp
  Results:
  - Dataset: COCO
    Metrics:
      AP: 0.767
      AP@0.5: 0.906
      AP@0.75: 0.834
      AR: 0.817
      AR@0.5: 0.945
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/udp/hrnet_w48_coco_256x192_udp-2554c524_20210223.pth
- Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/hrnet_w48_coco_384x288_udp.py
  In Collection: UDP
  Metadata:
    Architecture: *id001
    Training Data: COCO
  Name: topdown_heatmap_hrnet_w48_coco_384x288_udp
  Results:
  - Dataset: COCO
    Metrics:
      AP: 0.772
      AP@0.5: 0.91
      AP@0.75: 0.835
      AR: 0.82
      AR@0.5: 0.945
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/udp/hrnet_w48_coco_384x288_udp-0f89c63e_20210223.pth
- Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/hrnet_w32_coco_256x192_udp_regress.py
  In Collection: UDP
  Metadata:
    Architecture: *id001
    Training Data: COCO
  Name: topdown_heatmap_hrnet_w32_coco_256x192_udp_regress
  Results:
  - Dataset: COCO
    Metrics:
      AP: 0.758
      AP@0.5: 0.908
      AP@0.75: 0.823
      AR: 0.812
      AR@0.5: 0.943
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/udp/hrnet_w32_coco_256x192_udp_regress-be2dbba4_20210222.pth
