Collections:
- Name: DarkPose
  Paper:
    Title: Distribution-aware coordinate representation for human pose estimation
    URL: http://openaccess.thecvf.com/content_CVPR_2020/html/Zhang_Distribution-Aware_Coordinate_Representation_for_Human_Pose_Estimation_CVPR_2020_paper.html
  README: https://github.com/open-mmlab/mmpose/blob/master/docs/en/papers/techniques/dark.md
Models:
- Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/hrnet_w32_coco_256x192_dark.py
  In Collection: DarkPose
  Metadata:
    Architecture: &id001
    - HRNet
    - DarkPose
    Training Data: COCO
  Name: topdown_heatmap_hrnet_w32_coco_256x192_dark
  Results:
  - Dataset: COCO
    Metrics:
      AP: 0.757
      AP@0.5: 0.907
      AP@0.75: 0.823
      AR: 0.808
      AR@0.5: 0.943
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/hrnet/hrnet_w32_coco_256x192_dark-07f147eb_20200812.pth
- Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/hrnet_w32_coco_384x288_dark.py
  In Collection: DarkPose
  Metadata:
    Architecture: *id001
    Training Data: COCO
  Name: topdown_heatmap_hrnet_w32_coco_384x288_dark
  Results:
  - Dataset: COCO
    Metrics:
      AP: 0.766
      AP@0.5: 0.907
      AP@0.75: 0.831
      AR: 0.815
      AR@0.5: 0.943
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/hrnet/hrnet_w32_coco_384x288_dark-307dafc2_20210203.pth
- Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/hrnet_w48_coco_256x192_dark.py
  In Collection: DarkPose
  Metadata:
    Architecture: *id001
    Training Data: COCO
  Name: topdown_heatmap_hrnet_w48_coco_256x192_dark
  Results:
  - Dataset: COCO
    Metrics:
      AP: 0.764
      AP@0.5: 0.907
      AP@0.75: 0.83
      AR: 0.814
      AR@0.5: 0.943
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/hrnet/hrnet_w48_coco_256x192_dark-8cba3197_20200812.pth
- Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/hrnet_w48_coco_384x288_dark.py
  In Collection: DarkPose
  Metadata:
    Architecture: *id001
    Training Data: COCO
  Name: topdown_heatmap_hrnet_w48_coco_384x288_dark
  Results:
  - Dataset: COCO
    Metrics:
      AP: 0.772
      AP@0.5: 0.91
      AP@0.75: 0.836
      AR: 0.82
      AR@0.5: 0.946
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/hrnet/hrnet_w48_coco_384x288_dark-e881a4b6_20210203.pth
