Collections:
- Name: LiteHRNet
  Paper:
    Title: 'Lite-HRNet: A Lightweight High-Resolution Network'
    URL: https://arxiv.org/abs/2104.06403
  README: https://github.com/open-mmlab/mmpose/blob/master/docs/en/papers/backbones/litehrnet.md
Models:
- Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/litehrnet_18_coco_256x192.py
  In Collection: LiteHRNet
  Metadata:
    Architecture: &id001
    - LiteHRNet
    Training Data: COCO
  Name: topdown_heatmap_litehrnet_18_coco_256x192
  Results:
  - Dataset: COCO
    Metrics:
      AP: 0.643
      AP@0.5: 0.868
      AP@0.75: 0.72
      AR: 0.706
      AR@0.5: 0.912
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/litehrnet/litehrnet18_coco_256x192-6bace359_20211230.pth
- Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/litehrnet_18_coco_384x288.py
  In Collection: LiteHRNet
  Metadata:
    Architecture: *id001
    Training Data: COCO
  Name: topdown_heatmap_litehrnet_18_coco_384x288
  Results:
  - Dataset: COCO
    Metrics:
      AP: 0.677
      AP@0.5: 0.878
      AP@0.75: 0.746
      AR: 0.735
      AR@0.5: 0.92
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/litehrnet/litehrnet18_coco_384x288-8d4dac48_20211230.pth
- Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/litehrnet_30_coco_256x192.py
  In Collection: LiteHRNet
  Metadata:
    Architecture: *id001
    Training Data: COCO
  Name: topdown_heatmap_litehrnet_30_coco_256x192
  Results:
  - Dataset: COCO
    Metrics:
      AP: 0.675
      AP@0.5: 0.881
      AP@0.75: 0.754
      AR: 0.736
      AR@0.5: 0.924
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/litehrnet/litehrnet30_coco_256x192-4176555b_20210626.pth
- Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/litehrnet_30_coco_384x288.py
  In Collection: LiteHRNet
  Metadata:
    Architecture: *id001
    Training Data: COCO
  Name: topdown_heatmap_litehrnet_30_coco_384x288
  Results:
  - Dataset: COCO
    Metrics:
      AP: 0.7
      AP@0.5: 0.884
      AP@0.75: 0.776
      AR: 0.758
      AR@0.5: 0.928
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/litehrnet/litehrnet30_coco_384x288-a3aef5c4_20210626.pth
