Collections:
- Name: MobilenetV2
  Paper:
    Title: 'Mobilenetv2: Inverted residuals and linear bottlenecks'
    URL: http://openaccess.thecvf.com/content_cvpr_2018/html/Sandler_MobileNetV2_Inverted_Residuals_CVPR_2018_paper.html
  README: https://github.com/open-mmlab/mmpose/blob/master/docs/en/papers/backbones/mobilenetv2.md
Models:
- Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/mobilenetv2_coco_256x192.py
  In Collection: MobilenetV2
  Metadata:
    Architecture: &id001
    - MobilenetV2
    Training Data: COCO
  Name: topdown_heatmap_mobilenetv2_coco_256x192
  Results:
  - Dataset: COCO
    Metrics:
      AP: 0.646
      AP@0.5: 0.874
      AP@0.75: 0.723
      AR: 0.707
      AR@0.5: 0.917
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/mobilenetv2/mobilenetv2_coco_256x192-d1e58e7b_20200727.pth
- Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/mobilenetv2_coco_384x288.py
  In Collection: MobilenetV2
  Metadata:
    Architecture: *id001
    Training Data: COCO
  Name: topdown_heatmap_mobilenetv2_coco_384x288
  Results:
  - Dataset: COCO
    Metrics:
      AP: 0.673
      AP@0.5: 0.879
      AP@0.75: 0.743
      AR: 0.729
      AR@0.5: 0.916
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/mobilenetv2/mobilenetv2_coco_384x288-26be4816_20200727.pth
