Collections:
- Name: ResNetV1D
  Paper:
    Title: Bag of tricks for image classification with convolutional neural networks
    URL: http://openaccess.thecvf.com/content_CVPR_2019/html/He_Bag_of_Tricks_for_Image_Classification_with_Convolutional_Neural_Networks_CVPR_2019_paper.html
  README: https://github.com/open-mmlab/mmpose/blob/master/docs/en/papers/backbones/resnetv1d.md
Models:
- Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/resnetv1d50_coco_256x192.py
  In Collection: ResNetV1D
  Metadata:
    Architecture: &id001
    - ResNetV1D
    Training Data: COCO
  Name: topdown_heatmap_resnetv1d50_coco_256x192
  Results:
  - Dataset: COCO
    Metrics:
      AP: 0.722
      AP@0.5: 0.897
      AP@0.75: 0.799
      AR: 0.777
      AR@0.5: 0.933
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/resnetv1d/resnetv1d50_coco_256x192-a243b840_20200727.pth
- Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/resnetv1d50_coco_384x288.py
  In Collection: ResNetV1D
  Metadata:
    Architecture: *id001
    Training Data: COCO
  Name: topdown_heatmap_resnetv1d50_coco_384x288
  Results:
  - Dataset: COCO
    Metrics:
      AP: 0.73
      AP@0.5: 0.9
      AP@0.75: 0.799
      AR: 0.78
      AR@0.5: 0.934
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/resnetv1d/resnetv1d50_coco_384x288-01f3fbb9_20200727.pth
- Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/resnetv1d101_coco_256x192.py
  In Collection: ResNetV1D
  Metadata:
    Architecture: *id001
    Training Data: COCO
  Name: topdown_heatmap_resnetv1d101_coco_256x192
  Results:
  - Dataset: COCO
    Metrics:
      AP: 0.731
      AP@0.5: 0.899
      AP@0.75: 0.809
      AR: 0.786
      AR@0.5: 0.938
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/resnetv1d/resnetv1d101_coco_256x192-5bd08cab_20200727.pth
- Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/resnetv1d101_coco_384x288.py
  In Collection: ResNetV1D
  Metadata:
    Architecture: *id001
    Training Data: COCO
  Name: topdown_heatmap_resnetv1d101_coco_384x288
  Results:
  - Dataset: COCO
    Metrics:
      AP: 0.748
      AP@0.5: 0.902
      AP@0.75: 0.816
      AR: 0.799
      AR@0.5: 0.939
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/resnetv1d/resnetv1d101_coco_384x288-5f9e421d_20200730.pth
- Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/resnetv1d152_coco_256x192.py
  In Collection: ResNetV1D
  Metadata:
    Architecture: *id001
    Training Data: COCO
  Name: topdown_heatmap_resnetv1d152_coco_256x192
  Results:
  - Dataset: COCO
    Metrics:
      AP: 0.737
      AP@0.5: 0.902
      AP@0.75: 0.812
      AR: 0.791
      AR@0.5: 0.94
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/resnetv1d/resnetv1d152_coco_256x192-c4df51dc_20200727.pth
- Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/resnetv1d152_coco_384x288.py
  In Collection: ResNetV1D
  Metadata:
    Architecture: *id001
    Training Data: COCO
  Name: topdown_heatmap_resnetv1d152_coco_384x288
  Results:
  - Dataset: COCO
    Metrics:
      AP: 0.752
      AP@0.5: 0.909
      AP@0.75: 0.821
      AR: 0.802
      AR@0.5: 0.944
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/resnetv1d/resnetv1d152_coco_384x288-626c622d_20200730.pth
