Collections:
- Name: ResNeSt
  Paper:
    Title: 'ResNeSt: Split-Attention Networks'
    URL: https://arxiv.org/abs/2004.08955
  README: https://github.com/open-mmlab/mmpose/blob/master/docs/en/papers/backbones/resnest.md
Models:
- Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/resnest50_coco_256x192.py
  In Collection: ResNeSt
  Metadata:
    Architecture: &id001
    - ResNeSt
    Training Data: COCO
  Name: topdown_heatmap_resnest50_coco_256x192
  Results:
  - Dataset: COCO
    Metrics:
      AP: 0.721
      AP@0.5: 0.899
      AP@0.75: 0.802
      AR: 0.776
      AR@0.5: 0.938
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/resnest/resnest50_coco_256x192-6e65eece_20210320.pth
- Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/resnest50_coco_384x288.py
  In Collection: ResNeSt
  Metadata:
    Architecture: *id001
    Training Data: COCO
  Name: topdown_heatmap_resnest50_coco_384x288
  Results:
  - Dataset: COCO
    Metrics:
      AP: 0.737
      AP@0.5: 0.9
      AP@0.75: 0.811
      AR: 0.789
      AR@0.5: 0.938
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/resnest/resnest50_coco_384x288-dcd20436_20210320.pth
- Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/resnest101_coco_256x192.py
  In Collection: ResNeSt
  Metadata:
    Architecture: *id001
    Training Data: COCO
  Name: topdown_heatmap_resnest101_coco_256x192
  Results:
  - Dataset: COCO
    Metrics:
      AP: 0.725
      AP@0.5: 0.899
      AP@0.75: 0.807
      AR: 0.781
      AR@0.5: 0.939
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/resnest/resnest101_coco_256x192-2ffcdc9d_20210320.pth
- Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/resnest101_coco_384x288.py
  In Collection: ResNeSt
  Metadata:
    Architecture: *id001
    Training Data: COCO
  Name: topdown_heatmap_resnest101_coco_384x288
  Results:
  - Dataset: COCO
    Metrics:
      AP: 0.746
      AP@0.5: 0.906
      AP@0.75: 0.82
      AR: 0.798
      AR@0.5: 0.943
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/resnest/resnest101_coco_384x288-80660658_20210320.pth
- Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/resnest200_coco_256x192.py
  In Collection: ResNeSt
  Metadata:
    Architecture: *id001
    Training Data: COCO
  Name: topdown_heatmap_resnest200_coco_256x192
  Results:
  - Dataset: COCO
    Metrics:
      AP: 0.732
      AP@0.5: 0.905
      AP@0.75: 0.812
      AR: 0.787
      AR@0.5: 0.942
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/resnest/resnest200_coco_256x192-db007a48_20210517.pth
- Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/resnest200_coco_384x288.py
  In Collection: ResNeSt
  Metadata:
    Architecture: *id001
    Training Data: COCO
  Name: topdown_heatmap_resnest200_coco_384x288
  Results:
  - Dataset: COCO
    Metrics:
      AP: 0.754
      AP@0.5: 0.908
      AP@0.75: 0.827
      AR: 0.807
      AR@0.5: 0.945
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/resnest/resnest200_coco_384x288-b5bb76cb_20210517.pth
- Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/resnest269_coco_256x192.py
  In Collection: ResNeSt
  Metadata:
    Architecture: *id001
    Training Data: COCO
  Name: topdown_heatmap_resnest269_coco_256x192
  Results:
  - Dataset: COCO
    Metrics:
      AP: 0.738
      AP@0.5: 0.907
      AP@0.75: 0.819
      AR: 0.793
      AR@0.5: 0.945
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/resnest/resnest269_coco_256x192-2a7882ac_20210517.pth
- Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/resnest269_coco_384x288.py
  In Collection: ResNeSt
  Metadata:
    Architecture: *id001
    Training Data: COCO
  Name: topdown_heatmap_resnest269_coco_384x288
  Results:
  - Dataset: COCO
    Metrics:
      AP: 0.755
      AP@0.5: 0.908
      AP@0.75: 0.828
      AR: 0.806
      AR@0.5: 0.943
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/resnest/resnest269_coco_384x288-b142b9fb_20210517.pth
