Collections:
- Name: DarkPose
  Paper:
    Title: Distribution-aware coordinate representation for human pose estimation
    URL: http://openaccess.thecvf.com/content_CVPR_2020/html/Zhang_Distribution-Aware_Coordinate_Representation_for_Human_Pose_Estimation_CVPR_2020_paper.html
  README: https://github.com/open-mmlab/mmpose/blob/master/docs/en/papers/techniques/dark.md
Models:
- Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/res50_coco_256x192_dark.py
  In Collection: DarkPose
  Metadata:
    Architecture: &id001
    - SimpleBaseline2D
    - ResNet
    - DarkPose
    Training Data: COCO
  Name: topdown_heatmap_res50_coco_256x192_dark
  Results:
  - Dataset: COCO
    Metrics:
      AP: 0.724
      AP@0.5: 0.898
      AP@0.75: 0.8
      AR: 0.777
      AR@0.5: 0.936
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/resnet/res50_coco_256x192_dark-43379d20_20200709.pth
- Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/res50_coco_384x288_dark.py
  In Collection: DarkPose
  Metadata:
    Architecture: *id001
    Training Data: COCO
  Name: topdown_heatmap_res50_coco_384x288_dark
  Results:
  - Dataset: COCO
    Metrics:
      AP: 0.735
      AP@0.5: 0.9
      AP@0.75: 0.801
      AR: 0.785
      AR@0.5: 0.937
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/resnet/res50_coco_384x288_dark-33d3e5e5_20210203.pth
- Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/res101_coco_256x192_dark.py
  In Collection: DarkPose
  Metadata:
    Architecture: *id001
    Training Data: COCO
  Name: topdown_heatmap_res101_coco_256x192_dark
  Results:
  - Dataset: COCO
    Metrics:
      AP: 0.732
      AP@0.5: 0.899
      AP@0.75: 0.808
      AR: 0.786
      AR@0.5: 0.938
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/resnet/res101_coco_256x192_dark-64d433e6_20200812.pth
- Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/res101_coco_384x288_dark.py
  In Collection: DarkPose
  Metadata:
    Architecture: *id001
    Training Data: COCO
  Name: topdown_heatmap_res101_coco_384x288_dark
  Results:
  - Dataset: COCO
    Metrics:
      AP: 0.749
      AP@0.5: 0.902
      AP@0.75: 0.816
      AR: 0.799
      AR@0.5: 0.939
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/resnet/res101_coco_384x288_dark-cb45c88d_20210203.pth
- Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/res152_coco_256x192_dark.py
  In Collection: DarkPose
  Metadata:
    Architecture: *id001
    Training Data: COCO
  Name: topdown_heatmap_res152_coco_256x192_dark
  Results:
  - Dataset: COCO
    Metrics:
      AP: 0.745
      AP@0.5: 0.905
      AP@0.75: 0.821
      AR: 0.797
      AR@0.5: 0.942
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/resnet/res152_coco_256x192_dark-ab4840d5_20200812.pth
- Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/res152_coco_384x288_dark.py
  In Collection: DarkPose
  Metadata:
    Architecture: *id001
    Training Data: COCO
  Name: topdown_heatmap_res152_coco_384x288_dark
  Results:
  - Dataset: COCO
    Metrics:
      AP: 0.757
      AP@0.5: 0.909
      AP@0.75: 0.826
      AR: 0.806
      AR@0.5: 0.943
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/resnet/res152_coco_384x288_dark-d3b8ebd7_20210203.pth
