Collections:
- Name: RSN
  Paper:
    Title: Learning Delicate Local Representations for Multi-Person Pose Estimation
    URL: https://link.springer.com/chapter/10.1007/978-3-030-58580-8_27
  README: https://github.com/open-mmlab/mmpose/blob/master/docs/en/papers/backbones/rsn.md
Models:
- Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/rsn18_coco_256x192.py
  In Collection: RSN
  Metadata:
    Architecture: &id001
    - RSN
    Training Data: COCO
  Name: topdown_heatmap_rsn18_coco_256x192
  Results:
  - Dataset: COCO
    Metrics:
      AP: 0.704
      AP@0.5: 0.887
      AP@0.75: 0.779
      AR: 0.771
      AR@0.5: 0.926
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/rsn/rsn18_coco_256x192-72f4b4a7_20201127.pth
- Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/rsn50_coco_256x192.py
  In Collection: RSN
  Metadata:
    Architecture: *id001
    Training Data: COCO
  Name: topdown_heatmap_rsn50_coco_256x192
  Results:
  - Dataset: COCO
    Metrics:
      AP: 0.723
      AP@0.5: 0.896
      AP@0.75: 0.8
      AR: 0.788
      AR@0.5: 0.934
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/rsn/rsn50_coco_256x192-72ffe709_20201127.pth
- Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/2xrsn50_coco_256x192.py
  In Collection: RSN
  Metadata:
    Architecture: *id001
    Training Data: COCO
  Name: topdown_heatmap_2xrsn50_coco_256x192
  Results:
  - Dataset: COCO
    Metrics:
      AP: 0.745
      AP@0.5: 0.899
      AP@0.75: 0.818
      AR: 0.809
      AR@0.5: 0.939
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/rsn/2xrsn50_coco_256x192-50648f0e_20201127.pth
- Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/3xrsn50_coco_256x192.py
  In Collection: RSN
  Metadata:
    Architecture: *id001
    Training Data: COCO
  Name: topdown_heatmap_3xrsn50_coco_256x192
  Results:
  - Dataset: COCO
    Metrics:
      AP: 0.75
      AP@0.5: 0.9
      AP@0.75: 0.823
      AR: 0.813
      AR@0.5: 0.94
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/rsn/3xrsn50_coco_256x192-58f57a68_20201127.pth
