Collections:
- Name: ShufflenetV2
  Paper:
    Title: 'Shufflenet v2: Practical guidelines for efficient cnn architecture design'
    URL: http://openaccess.thecvf.com/content_ECCV_2018/html/Ningning_Light-weight_CNN_Architecture_ECCV_2018_paper.html
  README: https://github.com/open-mmlab/mmpose/blob/master/docs/en/papers/backbones/shufflenetv2.md
Models:
- Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/shufflenetv2_coco_256x192.py
  In Collection: ShufflenetV2
  Metadata:
    Architecture: &id001
    - ShufflenetV2
    Training Data: COCO
  Name: topdown_heatmap_shufflenetv2_coco_256x192
  Results:
  - Dataset: COCO
    Metrics:
      AP: 0.599
      AP@0.5: 0.854
      AP@0.75: 0.663
      AR: 0.664
      AR@0.5: 0.899
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/shufflenetv2/shufflenetv2_coco_256x192-0aba71c7_20200921.pth
- Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/shufflenetv2_coco_384x288.py
  In Collection: ShufflenetV2
  Metadata:
    Architecture: *id001
    Training Data: COCO
  Name: topdown_heatmap_shufflenetv2_coco_384x288
  Results:
  - Dataset: COCO
    Metrics:
      AP: 0.636
      AP@0.5: 0.865
      AP@0.75: 0.705
      AR: 0.697
      AR@0.5: 0.909
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/shufflenetv2/shufflenetv2_coco_384x288-fb38ac3a_20200921.pth
