Collections:
- Name: VGG
  Paper:
    Title: Very deep convolutional networks for large-scale image recognition
    URL: https://arxiv.org/abs/1409.1556
  README: https://github.com/open-mmlab/mmpose/blob/master/docs/en/papers/backbones/vgg.md
Models:
- Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/vgg16_bn_coco_256x192.py
  In Collection: VGG
  Metadata:
    Architecture:
    - VGG
    Training Data: COCO
  Name: topdown_heatmap_vgg16_bn_coco_256x192
  Results:
  - Dataset: COCO
    Metrics:
      AP: 0.698
      AP@0.5: 0.89
      AP@0.75: 0.768
      AR: 0.754
      AR@0.5: 0.929
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/vgg/vgg16_bn_coco_256x192-7e7c58d6_20210517.pth
