Collections:
- Name: ViPNAS
  Paper:
    Title: 'ViPNAS: Efficient Video Pose Estimation via Neural Architecture Search'
    URL: https://arxiv.org/abs/2105.10154
  README: https://github.com/open-mmlab/mmpose/blob/master/docs/en/papers/backbones/vipnas.md
Models:
- Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/vipnas_mbv3_coco_256x192.py
  In Collection: ViPNAS
  Metadata:
    Architecture: &id001
    - ViPNAS
    Training Data: COCO
  Name: topdown_heatmap_vipnas_mbv3_coco_256x192
  Results:
  - Dataset: COCO
    Metrics:
      AP: 0.7
      AP@0.5: 0.887
      AP@0.75: 0.778
      AR: 0.757
      AR@0.5: 0.929
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/vipnas/vipnas_mbv3_coco_256x192-7018731a_20211122.pth
- Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/vipnas_res50_coco_256x192.py
  In Collection: ViPNAS
  Metadata:
    Architecture: *id001
    Training Data: COCO
  Name: topdown_heatmap_vipnas_res50_coco_256x192
  Results:
  - Dataset: COCO
    Metrics:
      AP: 0.711
      AP@0.5: 0.893
      AP@0.75: 0.789
      AR: 0.769
      AR@0.5: 0.934
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/vipnas/vipnas_res50_coco_256x192-cc43b466_20210624.pth
