Collections:
- Name: SimpleBaseline2D
  Paper:
    Title: Simple baselines for human pose estimation and tracking
    URL: http://openaccess.thecvf.com/content_ECCV_2018/html/Bin_Xiao_Simple_Baselines_for_ECCV_2018_paper.html
  README: https://github.com/open-mmlab/mmpose/blob/master/docs/en/papers/algorithms/simplebaseline2d.md
Models:
- Config: configs/hand/2d_kpt_sview_rgb_img/topdown_heatmap/freihand2d/res50_freihand_224x224.py
  In Collection: SimpleBaseline2D
  Metadata:
    Architecture: &id001
    - SimpleBaseline2D
    - ResNet
    Training Data: FreiHand
  Name: topdown_heatmap_res50_freihand_224x224
  Results:
  - Dataset: FreiHand
    Metrics:
      AUC: 0.868
      EPE: 3.25
      PCK@0.2: 0.993
    Task: Hand 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/hand/resnet/res50_freihand_224x224-ff0799bc_20200914.pth
- Config: configs/hand/2d_kpt_sview_rgb_img/topdown_heatmap/freihand2d/res50_freihand_224x224.py
  In Collection: SimpleBaseline2D
  Metadata:
    Architecture: *id001
    Training Data: FreiHand
  Name: topdown_heatmap_res50_freihand_224x224
  Results:
  - Dataset: FreiHand
    Metrics:
      AUC: 0.868
      EPE: 3.27
      PCK@0.2: 0.992
    Task: Hand 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/hand/resnet/res50_freihand_224x224-ff0799bc_20200914.pth
